/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[4],{489:function(Ba,va,r){var oa=r(0);Ba=r(85);var ka=r(49);r=function(la){function fa(){return null!==la&&la.apply(this,arguments)||this}Object(oa.c)(fa,la);fa.prototype.testSelection=function(ea,ca,x){return ka.a.sl(ea,ca,x)};return fa}(Ba.a);va.a=r},89:function(Ba,va,r){function oa(xa,Ka,Oa,Pa,Xa){return Object(ra.b)(void 0,void 0,void 0,function(){var ab,cb,ib,lb,ob,rb,tb,yb,Nb;return Object(ra.d)(this,function(Jb){switch(Jb.label){case 0:return ab=
Ua.getDocument(),cb=[1],[4,Object(ua.c)(Ka,{extension:"pdf"})];case 1:return ib=Jb.da(),lb=Ua.na(),tb=(rb=Va.a).ria,[4,ib.tC()];case 2:return ob=tb.apply(rb,[Jb.da().xfdfString,xa]),yb=!0,[4,ab.If(ib,cb,xa,yb)];case 3:return Jb.da(),[4,ab.zg([xa+1],yb)];case 4:return Jb.da(),Nb=lb.ub().filter(function(Lb){return Lb.RK()&&Lb.PageNumber===xa}),lb.jg(Nb,{force:!0,source:"contentEditTool"}),[4,lb.yK(ob)];case 5:return Jb.da(),Ua.getDocument().mM(),Ua.lM(xa),Ua.Xe(),ea(xa),Xa||(da(xa,Oa.galleys,Pa),da(xa,
Oa.objects,Pa)),[2]}})})}function ka(xa){xa=(new DOMParser).parseFromString(xa,"text/html").documentElement.querySelector("body");xa.querySelectorAll("p").forEach(function(Ka){Ka.querySelectorAll("span").forEach(function(Xa){var ab=Xa.getAttribute("style");ab=la(ab,Xa.innerHTML);Xa.innerHTML=ab});var Oa=Ka.getAttribute("style"),Pa=Ka.innerHTML.replaceAll("<br>","");Ka.innerHTML=la(Oa,Pa)});return xa.innerHTML.trim()}function la(xa,Ka){if(null===xa||void 0===xa?0:xa.includes("bold"))Ka="<strong>"+
Ka+"</strong>";if(null===xa||void 0===xa?0:xa.includes("italic"))Ka="<em>"+Ka+"</em>";if((null===xa||void 0===xa?0:xa.includes("underline:1;"))||(null===xa||void 0===xa?0:xa.includes("text-decoration: underline")))Ka="<u>"+Ka+"</u>";return Ka}function fa(xa){if(["STRONG","EM","U"].includes(xa.tagName)&&null!==xa.getAttribute("style")){var Ka=document.createElement("span"),Oa=xa.style.color;Oa=w(Oa);Ka.setAttribute("style","color:"+Oa);xa.removeAttribute("style");Ka.innerHTML=xa.innerHTML;xa.innerHTML=
"";xa.appendChild(Ka)}else"SPAN"===xa.tagName&&null!==xa.getAttribute("style")?(Oa=xa.style.color,Oa=w(Oa),xa.setAttribute("style","color:"+Oa)):"A"===xa.tagName&&xa.removeAttribute("style")}function ea(xa){var Ka=Ua.na(),Oa=Ka.ub().filter(function(Pa){return Pa.Jf()&&Pa.PageNumber===xa});Ka.jg(Oa,{force:!0,source:"contentEditTool"})}function ca(xa,Ka){Ka.forEach(function(Oa){Ga[xa]||(Ga[xa]=[]);Ga[xa].find(function(Pa){return Pa.id===Oa.id})||Ga[xa].push(Oa)})}function x(xa,Ka){Ka.forEach(function(Oa){Ea[xa]||
(Ea[xa]=[]);Ea[xa].find(function(Pa){return Pa.id===Oa.id})||Ea[xa].push(Oa)})}function y(xa,Ka){return Object(ra.b)(void 0,void 0,void 0,function(){var Oa,Pa,Xa,ab,cb,ib,lb,ob,rb,tb,yb,Nb,Jb,Lb,Qb,za,Sa,bb;return Object(ra.d)(this,function(gb){switch(gb.label){case 0:if(!xa)return[2];Oa=Ka.replaceAll("<p><br></p>","");Pa=h(Oa);Pa=Pa.replace(/<span style="color: var\(--text-color\);">(.*?)<\/span>/g,"$1");Pa=Pa.replace(/<span class="ql-cursor">(.*?)<\/span>/g,"");Xa=xa.yf.id;ab=xa.PageNumber;cb=Qa[ab];
ib=cb.galleys.find(function(mb){return mb.id===Xa});lb=ka(ib.contents);ob=z(ab,cb,lb,Pa,Xa);if(""===ob)return[3,2];rb=new TextEncoder;tb=rb.encode(ob);yb=tb.buffer;Nb=Object(Aa.c)()||"https://www.pdftron.com/webfonts/v2/";Jb=Ua.getDocument();return[4,Jb.Yd([ab])];case 1:return Lb=gb.da(),rb=new TextEncoder,Qb=rb.encode(""),za=Qb.buffer,Na.postMessage({cmd:"importText",pdfFile:Lb,pageNumber:ab,webFontURL:Nb,galleyId:Xa,importData:yb,tableData:za},[yb,za]),Sa={},ib&&(bb=ib.galleyBox,Sa={top:bb.top,
left:bb.left,bottom:bb.bottom,right:bb.right}),Object(Ja.v)(lb,Pa,Sa),[3,3];case 2:Object(Ia.g)("Unable to generate import XML"),gb.label=3;case 3:return[2]}})})}function h(xa){var Ka=new DOMParser,Oa=Ka.parseFromString(xa,"text/xml");Oa.querySelector("parsererror")&&(Oa=Ka.parseFromString("<Root>"+xa+"</Root>","text/xml"));Oa.querySelectorAll("a").forEach(function(Pa){var Xa=Pa.childNodes[0];Array.from(Pa.querySelectorAll("*")).find(function(ab){return"u"===ab.tagName.toLowerCase()})||(Pa=document.createElement("u"),
Xa.after(Pa),Pa.appendChild(Xa))});return(new XMLSerializer).serializeToString(Oa)}function e(xa,Ka,Oa,Pa){this.top=xa;this.left=Ka;this.bottom=Oa;this.right=Pa;this.topVal=function(){return Math.round(this.top)};this.bottomVal=function(){return Math.round(this.bottom)};this.leftVal=function(){return Math.round(this.left)};this.rightVal=function(){return Math.round(this.right)};this.height=function(){return Math.round(Math.abs(this.top-this.bottom))};this.width=function(){return Math.round(this.right-
this.left)};this.RR=function(Xa){return this.topVal()!==Xa.topVal()||this.leftVal()!==Xa.leftVal()||this.bottomVal()!==Xa.bottomVal()||this.rightVal()!==Xa.rightVal()}}function b(xa,Ka,Oa,Pa,Xa){this.id=xa;this.pagenum=Ka;this.galleysContents=Oa;this.contents=Pa;this.galleyBox=Xa;Object(Ja.u)(Ea)}function a(xa,Ka,Oa,Pa){this.id=Ka;this.type=xa;this.bbox=Oa;this.pagenum=Pa}function f(xa,Ka,Oa,Pa,Xa){this.id=xa;this.pagecount=Ka;this.pageBBox=Oa;this.galleys=Pa;this.objects=Xa}function n(xa,Ka){this.family=
xa;this.variations=Ka}function z(xa,Ka,Oa,Pa,Xa){var ab=[],cb=[];(new DOMParser).parseFromString(Pa,"text/html").documentElement.querySelectorAll("p").forEach(function(tb,yb){ab[yb]=tb.innerHTML;cb[yb]={fontSize:tb.style.fontSize,fontFamily:tb.style.fontFamily,color:w(tb.style.color)}});Oa=(new DOMParser).parseFromString(Oa,"text/html");var ib=null;Oa.documentElement.querySelectorAll("p").forEach(function(tb,yb){if(yb<ab.length){var Nb=(new DOMParser).parseFromString(ab[yb],"text/html").documentElement.querySelector("body");
Nb.childNodes.forEach(function(Lb){fa(Lb)});tb.innerHTML=Nb.innerHTML;ib=tb.getAttribute("style");Nb=cb[yb].fontSize?cb[yb].fontSize:tb.style.fontSize;var Jb=cb[yb].fontFamily?cb[yb].fontFamily.replace(/\s+/g,"").replace(/['"]+/g,""):tb.style.fontFamily;yb=cb[yb].color?cb[yb].color:null;ib=ib.replace(/(font:.*?;)/i,"font:normal normal "+Nb+" "+Jb+";");ib=ib.replace("Italic","");ib=ib.replace("underline:1;","underline:0;");ib=ib.replace("text-decoration: underline;","text-decoration: none;");yb&&(ib=
ib.replace(/(color:.*?;)/i,"color:"+yb+";"));tb.setAttribute("style",ib)}else tb.remove()});for(Pa=Oa.documentElement.querySelectorAll("p").length;Pa<ab.length;Pa++){var lb=document.createElement("p");lb.setAttribute("id","0");var ob=(new DOMParser).parseFromString(ab[Pa],"text/html").documentElement.querySelector("body");ob.childNodes.forEach(function(tb){fa(tb)});lb.innerHTML=ob.innerHTML;null!=ib&&lb.setAttribute("style",ib);Oa.documentElement.querySelector("body").appendChild(lb)}Oa=Oa.documentElement.querySelector("body").innerHTML;
var rb="";Ea[xa].forEach(function(tb){tb.id===Xa&&(rb=tb)});if(""===rb)return"";Ka="<DOC id='"+Ka.id+"' pagecount='"+Ka.pagecount+"'>";Ka=Ka+("<STORY galley_ids='"+Xa+"' pagenum='"+xa+"'><galleys>")+(rb.galleysContents+"</galleys>");rb.contents=Oa;Ka=Ka+Oa+"\n</STORY>";return Ka+="</DOC>"}function w(xa){return xa.startsWith("rgb(")?"#"+xa.replace(/^[^\d]+/,"").replace(/[^\d]+$/,"").split(",").map(function(Ka){return("00"+parseInt(Ka,10).toString(16)).slice(-2)}).join(""):xa}function da(xa,Ka,Oa){var Pa=
[],Xa=Ua.getDocument(),ab=null;Ka.forEach(function(cb){if(cb instanceof a){var ib=Xa.bo(xa,cb.bbox.leftVal(),cb.bbox.topVal());var lb=ib.x;var ob=ib.y;var rb=Xa.bo(xa,cb.bbox.rightVal(),cb.bbox.bottomVal());ib=rb.x;rb=rb.y}else if(cb instanceof b)ib=Xa.bo(xa,cb.galleyBox.leftVal(),cb.galleyBox.topVal()),lb=ib.x,ob=ib.y,rb=Xa.bo(xa,cb.galleyBox.rightVal(),cb.galleyBox.bottomVal()),ib=rb.x,rb=rb.y;else return;var tb=new window.Core.Annotations.RectangleAnnotation,yb=Da.a.OBJECT;cb instanceof b&&(yb=
Da.a.TEXT);tb.cla(cb,yb);tb.PageNumber=cb.pagenum;tb.X=lb;tb.Y=ob;tb.Width=ib-lb;tb.Height=rb-ob;tb.StrokeColor=new pa.a("#3183C8");tb.FillColor=new pa.a(255,255,255,.01);tb.Style="dash";tb.Dashes="4,3";tb.ow();tb.selectionModel=wa.a;Pa.push(tb);"undefined"!==typeof Oa&&Oa===cb.id&&(ab=tb)});Ka=Ua.na();Ka.Tg(Pa);ab&&Ka.Pf(ab);Ka.he(Pa)}function ja(xa,Ka,Oa){return Object(ra.b)(this,void 0,void 0,function(){var Pa,Xa,ab,cb,ib,lb;return Object(ra.d)(this,function(ob){switch(ob.label){case 0:Pa=xa.data;
ab=Pa.cmd;switch(ab){case "isReady":return[3,1];case "initialiseInfixServer":return[3,3];case "loadAvailableFonts":return[3,4];case "exportFile":return[3,5];case "insertNewTextBox":return[3,6];case "importText":return[3,7];case "transformObject":return[3,7];case "alignParagraph":return[3,7];case "deleteObject":return[3,8];case "insertImage":return[3,9]}return[3,10];case 1:return[4,Object(Ha.b)()];case 2:return cb=ob.da(),Na.postMessage({cmd:"initialiseInfixServer",l:cb}),[3,10];case 3:return(ib=aa(Pa.resultsXML))?
(Ka(),lb=Object(Aa.c)()||"https://www.pdftron.com/webfonts/v2/",Na.postMessage({cmd:"loadAvailableFonts",webFontURL:lb})):Oa("License key does not have content edit permission"),[3,10];case 4:return qa(Pa.resultsXML),[3,10];case 5:return Pa.exportPerformed?ia(Pa.pageNumber,Pa.exportXML,Pa.objectXML,Pa.resultsXML):(Xa=Qa[Pa.pageNumber],x(Pa.pageNumber,Xa.galleys),ca(Pa.pageNumber,Xa.objects),ea(Pa.pageNumber),da(Pa.pageNumber,Xa.galleys),da(Pa.pageNumber,Xa.objects)),[3,10];case 6:return ba(Pa.pageNumber,
Pa.exportXML,Pa.contentHTML),Xa=Qa[Pa.pageNumber],oa(Pa.pageNumber,Pa.pdfBuffer,Xa,Pa.id),[3,10];case 7:return Xa=Qa[Pa.pageNumber],sa(Pa.pageNumber,Pa.resultsXML),oa(Pa.pageNumber,Pa.pdfBuffer,Xa,Pa.id),[3,10];case 8:return Xa=Qa[Pa.pageNumber],sa(Pa.pageNumber,Pa.resultsXML),Xa.galleys=Xa.galleys.filter(function(rb){return rb.id!==Pa.id}),Xa.objects=Xa.objects.filter(function(rb){return rb.id!==Pa.id}),oa(Pa.pageNumber,Pa.pdfBuffer,Xa),[3,10];case 9:return Xa=Qa[Pa.pageNumber],sa(Pa.pageNumber,
Pa.resultsXML),oa(Pa.pageNumber,Pa.pdfBuffer,Xa,Pa.isText,!0),[3,10];case 10:return[2]}})})}function aa(xa){xa=new Uint8Array(xa);var Ka=(new TextDecoder("utf-8")).decode(xa);xa=!1;Ka=(new DOMParser).parseFromString(Ka,"text/xml").getElementsByTagName("LicenseCheck");null!==Ka&&0<Ka.length&&(Ka=Ka[0].getElementsByTagName("Status")[0].innerHTML,"error"!==Ka&&"ok"===Ka&&(xa=!0));return xa}function ba(xa,Ka){Ka=(new TextDecoder("utf-8")).decode(Ka);Ka=(new DOMParser).parseFromString(Ka,"text/xml").getElementsByTagName("STORY");
var Oa=Array.prototype.slice.call(Ka)[0];Ka=Oa.getAttribute("galley_ids");var Pa=Array.prototype.slice.call(Oa.getElementsByTagName("g"))[0],Xa=Pa.getAttribute("bbox").split(" ");Xa=new e(parseFloat(Xa[0]),parseFloat(Xa[1]),parseFloat(Xa[2]),parseFloat(Xa[3]));Pa=Pa.innerHTML;var ab=Array.prototype.slice.call(Oa.getElementsByTagName("galleys"))[0];ab.parentNode.removeChild(ab);Oa=na(Oa.innerHTML).trim();Ka=new b(Ka,xa,Pa,Oa,Xa);Oa=Qa[xa];Xa=Oa.galleys;Xa.push(Ka);Oa.galleys=Xa;Qa[xa]=Oa;x(xa,Oa.galleys);
ca(xa,Oa.objects);ea(xa);da(xa,Oa.galleys);da(xa,Oa.objects)}function ia(xa,Ka,Oa,Pa){var Xa=new Uint8Array(Ka),ab=new TextDecoder("utf-8");Ka=ab.decode(Xa);Xa=new Uint8Array(Oa);Oa=ab.decode(Xa);Xa=new Uint8Array(Pa);Pa=ab.decode(Xa);Qa[xa]=ma(xa,Ka,Oa,Pa);Pa=Qa[xa];x(xa,Pa.galleys);ca(xa,Pa.objects);ea(xa);da(xa,Pa.galleys);da(xa,Pa.objects)}function ha(xa,Ka){xa=parseFloat(xa);return isNaN(Ka)||Ka<xa?xa:Ka}function ma(xa,Ka,Oa,Pa){var Xa;var ab=new DOMParser;Pa=ab.parseFromString(Pa,"text/xml");
Array.prototype.slice.call(Pa.getElementsByTagName("BBox")).forEach(function(lb){if("CropBox"===lb.getAttribute("Name")){var ob=parseFloat(lb.getElementsByTagName("Top").item(0).innerHTML),rb=parseFloat(lb.getElementsByTagName("Bottom").item(0).innerHTML),tb=parseFloat(lb.getElementsByTagName("Left").item(0).innerHTML);lb=parseFloat(lb.getElementsByTagName("Right").item(0).innerHTML);Xa=new e(ob,tb,rb,lb)}});ab=new DOMParser;Pa=ab.parseFromString(Ka,"text/xml");var cb=[];Array.prototype.slice.call(Pa.getElementsByTagName("STORY")).forEach(function(lb){var ob=
lb.getAttribute("galley_ids"),rb=Array.prototype.slice.call(lb.getElementsByTagName("g"))[0],tb=rb.getAttribute("bbox").split(" ");tb=new e(parseFloat(tb[0]),parseFloat(tb[1]),parseFloat(tb[2]),parseFloat(tb[3]));rb=rb.innerHTML;var yb=Array.prototype.slice.call(lb.getElementsByTagName("galleys"))[0];yb.parentNode.removeChild(yb);lb=na(lb.innerHTML).trim();ob=new b(ob,xa,rb,lb,tb);cb.push(ob)});ab=new DOMParser;var ib=[];Ka=ab.parseFromString(Oa,"text/xml").getElementsByTagName("Object");Array.prototype.slice.call(Ka).forEach(function(lb){var ob=
lb.getAttribute("Type"),rb=lb.getAttribute("OID");lb=Array.prototype.slice.call(lb.getElementsByTagName("Point"));var tb=Number.NaN,yb=Number.NaN,Nb=Number.NaN,Jb=Number.NaN;lb.forEach(function(Lb){var Qb=Lb.getAttribute("Name");"TL"===Qb?(tb=ha(Lb.getAttribute("Y"),tb),Nb=ha(Lb.getAttribute("X"),Nb)):"TR"===Qb?(tb=ha(Lb.getAttribute("Y"),tb),Jb=ha(Lb.getAttribute("X"),Jb)):"BR"===Qb?(yb=ha(Lb.getAttribute("Y"),yb),Jb=ha(Lb.getAttribute("X"),Jb)):"BL"===Qb&&(yb=ha(Lb.getAttribute("Y"),yb),Nb=ha(Lb.getAttribute("X"),
Nb))});lb=new e(tb,Nb,yb,Jb);ob=new a(ob,rb,lb,xa);ib.push(ob)});Ka=Array.prototype.slice.call(Pa.getElementsByTagName("DOC"))[0].getAttribute("id");return new f(Ka,1,Xa,cb,ib)}function na(xa){return(new DOMParser).parseFromString(xa,"text/html").documentElement.querySelector("body").innerHTML}function sa(xa,Ka){var Oa;Ka=(new TextDecoder("utf-8")).decode(Ka);var Pa=(new DOMParser).parseFromString(Ka,"text/xml");Ka=Pa.getElementsByTagName("Galley").item(0);if(null!=Ka){var Xa=Ka.getAttribute("id");
Ka=Pa.getElementsByTagName("BBox");Ka=Array.prototype.slice.call(Ka);Ka.forEach(function(ib){var lb=ib.getElementsByTagName("Top"),ob=parseFloat(lb.item(0).innerHTML);lb=ib.getElementsByTagName("Left");var rb=parseFloat(lb.item(0).innerHTML);lb=ib.getElementsByTagName("Bottom");var tb=parseFloat(lb.item(0).innerHTML);lb=ib.getElementsByTagName("Right");ib=parseFloat(lb.item(0).innerHTML);Oa=new e(ob,rb,tb,ib)});Ea[xa].forEach(function(ib){ib.id===Xa&&!0===Oa.RR(ib.galleyBox)&&(ib.galleyBox=Oa)})}Ka=
Pa.getElementsByTagName("Object").item(0);if(null!=Ka){var ab=Ka.getAttribute("OID");Ka=Pa.getElementsByTagName("BBox");Ka=Array.prototype.slice.call(Ka);Ka.forEach(function(ib){var lb=ib.getElementsByTagName("Top"),ob=parseFloat(lb.item(0).innerHTML);lb=ib.getElementsByTagName("Left");var rb=parseFloat(lb.item(0).innerHTML);lb=ib.getElementsByTagName("Bottom");var tb=parseFloat(lb.item(0).innerHTML);lb=ib.getElementsByTagName("Right");ib=parseFloat(lb.item(0).innerHTML);Oa=new e(ob,rb,tb,ib)});Ga[xa].forEach(function(ib){ib.id===
ab&&!0===Oa.RR(ib.bbox)&&(ib.bbox=Oa)})}Ka=Pa.getElementsByTagName("NewParas").item(0);if(null!=Ka){var cb=Ka.getAttribute("id");Ea[xa].forEach(function(ib){if(ib.id===cb){var lb="<Contents>"+ib.contents;lb+="</Contents>";var ob=Array.prototype.slice.call(Pa.getElementsByTagName("NewPara"));lb=(new DOMParser).parseFromString(lb,"text/xml");var rb=Array.prototype.slice.call(lb.getElementsByTagName("p"));ob.forEach(function(tb){var yb=parseFloat(tb.innerHTML),Nb=!1;rb.forEach(function(Jb){var Lb=Jb.getAttribute("id");
!1===Nb&&"0"===Lb&&(Jb.setAttribute("id",yb),Nb=!0)})});ib.contents=lb.getElementsByTagName("Contents").item(0).innerHTML}})}}function qa(xa){xa=new Uint8Array(xa);xa=(new TextDecoder("utf-8")).decode(xa);xa=(new DOMParser).parseFromString(xa,"text/xml").getElementsByTagName("Font");var Ka={};Array.prototype.slice.call(xa).forEach(function(Oa){var Pa=Oa.getAttribute("Family");Pa in Ka||(Ka[Pa]={});var Xa=[];Array.prototype.slice.call(Oa.getElementsByTagName("Variation")).forEach(function(ab){ab=ab.innerHTML;
Xa.push(ab);if(ab.includes("Regular")||ab===Pa.replace(/\s+/g,""))Ka[Pa].hasRegular=!0;ab.includes("Bold")&&(Ka[Pa].hasBold=!0);ab.includes("Italic")&&(Ka[Pa].hasItalic=!0)});Oa=new n(Pa,Xa);Wa.push(Oa)});$a=Object.keys(Ka).filter(function(Oa){return Ka[Oa].hasRegular&&Ka[Oa].hasBold&&Ka[Oa].hasItalic})}r.r(va);var ra=r(0),ua=r(55),pa=r(7),wa=r(489),Aa=r(37),Ha=r(78),Ia=r(2),Da=r(167),Ja=r(58),Va=r(6),Na=null,Ta=null,Ea={},Ga={},Qa={},Wa=[],$a=[],Ua;va["default"]={nia:function(xa){return Object(ra.b)(void 0,
void 0,void 0,function(){return Object(ra.d)(this,function(){Ta||(Ua=xa,Ta=new Promise(function(Ka,Oa){var Pa=window.Core.ContentEdit.getWorkerPath(),Xa=window.Core.ContentEdit.getResourcePath();Na=new Worker(Pa+"InfixServerModule.js");Na.onmessage=function(ab){ja(ab,Ka,Oa)};Na.postMessage({cmd:"isReady",resourcePath:Xa})}));return[2,Ta]})})},pia:function(xa,Ka,Oa){return Object(ra.b)(void 0,void 0,void 0,function(){var Pa,Xa,ab,cb;return Object(ra.d)(this,function(ib){switch(ib.label){case 0:return ea(Ka),
Ea[Ka]=[],Ga[Ka]=[],[4,xa.Yd([Ka])];case 1:return Pa=ib.da(),Xa=new TextEncoder,ab=Xa.encode(""),cb=ab.buffer,Na.postMessage({cmd:"exportFile",pageNumber:Ka,performExport:Oa,pdfFile:Pa,tableData:cb},[Pa,cb]),[2]}})})},Y8:function(xa){return Object(ra.b)(void 0,void 0,void 0,function(){var Ka,Oa,Pa,Xa,ab,cb,ib,lb;return Object(ra.d)(this,function(ob){switch(ob.label){case 0:return Ka=xa.id,Oa=xa.isText,Pa=xa.pageNumber,Xa=Ua.getDocument(),[4,Xa.Yd([Pa])];case 1:return ab=ob.da(),cb=new TextEncoder,
ib=cb.encode(""),lb=ib.buffer,Na.postMessage({cmd:"deleteObject",pdfFile:ab,pageNumber:Pa,objectID:Ka,isText:Oa,tableData:lb},[lb]),[2]}})})},Ona:function(xa){return Object(ra.b)(void 0,void 0,void 0,function(){var Ka,Oa,Pa,Xa,ab,cb,ib,lb,ob,rb,tb,yb,Nb;return Object(ra.d)(this,function(Jb){switch(Jb.label){case 0:return Ka=xa.id,Oa=xa.position,Pa=Oa.top,Xa=Oa.left,ab=Oa.bottom,cb=Oa.right,ib=xa.isText,lb=xa.pageNumber,ob=Ua.getDocument(),[4,ob.Yd([lb])];case 1:return rb=Jb.da(),tb=new TextEncoder,
yb=tb.encode(""),Nb=yb.buffer,Na.postMessage({cmd:"transformObject",pdfFile:rb,pageNumber:lb,objectID:Ka,isText:ib,topVal:Pa,leftVal:Xa,bottomVal:ab,rightVal:cb,tableData:Nb},[Nb]),[2]}})})},K5:function(xa,Ka){return Object(ra.b)(void 0,void 0,void 0,function(){var Oa,Pa,Xa,ab,cb,ib,lb,ob,rb,tb,yb,Nb,Jb,Lb,Qb;return Object(ra.d)(this,function(za){switch(za.label){case 0:return Oa="<DOC><STORY><galleys></galleys>",Pa=[],Xa=(new DOMParser).parseFromString(Ka,"text/html"),Xa.documentElement.querySelectorAll("p").forEach(function(Sa,
bb){Pa[bb]=Sa.innerHTML}),Pa.forEach(function(Sa,bb){Sa=(new DOMParser).parseFromString(Pa[bb],"text/html").documentElement.querySelector("body");Sa.childNodes.forEach(function(gb){fa(gb)});Oa+="<p>"+Sa.innerHTML+"</p>"}),Oa+="</STORY></DOC>",ab=xa.pageNumber,cb=Ua.getDocument(),ib=xa.position,lb=ib.top,ob=ib.left,rb=ib.bottom,tb=ib.right,yb=xa.defaultText,Nb=xa.font,Jb=xa.fontSize,Lb=xa.textColor,[4,cb.Yd([ab])];case 1:return Qb=za.da(),Na.postMessage({cmd:"insertNewTextBox",pdfFile:Qb,pageNumber:ab,
topVal:lb,leftVal:ob,bottomVal:rb,rightVal:tb,defaultText:yb,font:Nb,fontSize:Jb,textColor:Lb,importData:Oa,content:Ka}),[2]}})})},goa:y,qca:function(xa){if(xa)return ka(xa.contents);Object(Ia.g)("Unable to extract document content")},dla:function(xa,Ka){var Oa=ka(xa.yf.contents);Oa=(new DOMParser).parseFromString(Oa,"text/html").documentElement.querySelector("body");var Pa=Oa.querySelectorAll("p"),Xa=new XMLSerializer;Pa.forEach(function(ab){ab.style.fontFamily=Ka});Oa=Xa.serializeToString(Oa);y(xa,
Oa)},ela:function(xa,Ka){var Oa=ka(xa.yf.contents);Oa=(new DOMParser).parseFromString(Oa,"text/html").documentElement.querySelector("body");var Pa=Oa.querySelectorAll("p"),Xa=new XMLSerializer;Pa.forEach(function(ab){ab.style.fontSize=Ka});Oa=Xa.serializeToString(Oa);y(xa,Oa)},W5:function(xa,Ka){return Object(ra.b)(void 0,void 0,void 0,function(){var Oa,Pa,Xa,ab,cb,ib,lb;return Object(ra.d)(this,function(ob){switch(ob.label){case 0:return Oa=xa.yf.id,Pa=xa.PageNumber,Xa=Ua.getDocument(),[4,Xa.Yd([Pa])];
case 1:return ab=ob.da(),cb=new TextEncoder,ib=cb.encode(""),lb=ib.buffer,Na.postMessage({cmd:"AlignParaText",pdfFile:ab,pageNumber:Pa,galleyID:Oa,alignment:Ka,topVal1:"",leftVal1:"",bottomVal1:"",rightVal1:"",topVal2:"",leftVal2:"",bottomVal2:"",rightVal2:"",tableData:lb},[lb]),[2]}})})},M6:function(xa){var Ka=ka(xa.yf.contents);Ka=(new DOMParser).parseFromString(Ka,"text/html").documentElement.querySelector("body");var Oa=Ka.querySelectorAll("p"),Pa=new XMLSerializer,Xa="bold"===Oa[0].style.fontWeight,
ab=Pa.serializeToString(Oa[0]).includes("<strong>");Oa.forEach(function(cb){if(Xa||ab){cb.style.fontWeight="normal";var ib=Pa.serializeToString(cb).replace(/<strong>/g,"");ib=ib.replace(/<\/strong>/g,"");ib=(new DOMParser).parseFromString(ib,"text/html").documentElement.querySelector("p");cb.parentElement.replaceChild(ib,cb)}else cb.style.fontWeight="bold",cb.innerHTML="<strong>"+cb.innerHTML.trim()+"</strong>"});Ka=Pa.serializeToString(Ka);y(xa,Ka)},Wfa:function(xa){var Ka=ka(xa.yf.contents);Ka=
(new DOMParser).parseFromString(Ka,"text/html").documentElement.querySelector("body");var Oa=Ka.querySelectorAll("p"),Pa=new XMLSerializer,Xa="italic"===Oa[0].style.fontStyle,ab=Pa.serializeToString(Oa[0]).includes("<em>");Oa.forEach(function(cb){if(Xa||ab){cb.style.fontStyle="normal";cb.style.font.includes("Italic")&&(cb.style.font=cb.style.font.replace("Italic",""));var ib=Pa.serializeToString(cb).replace(/<em>/g,"");ib=ib.replace(/<\/em>/g,"");ib=(new DOMParser).parseFromString(ib,"text/html").documentElement.querySelector("p");
cb.parentElement.replaceChild(ib,cb)}else cb.style.fontStyle="italic",cb.innerHTML="<em>"+cb.innerHTML.trim()+"</em>"});Ka=Pa.serializeToString(Ka);y(xa,Ka)},Una:function(xa){var Ka=ka(xa.yf.contents);Ka=(new DOMParser).parseFromString(Ka,"text/html").documentElement.querySelector("body");var Oa=Ka.querySelectorAll("p"),Pa=new XMLSerializer,Xa=Oa[0].style.textDecoration.includes("underline")||Oa[0].style.textDecoration.includes("word"),ab=Pa.serializeToString(Oa[0]).includes("<u>");Oa.forEach(function(cb){if(Xa||
ab){cb.style.textDecoration=cb.style.textDecoration.replace("underline","");var ib=Pa.serializeToString(cb).replace(/<u>/g,"");ib=ib.replace(/<\/u>/g,"");ib=(new DOMParser).parseFromString(ib,"text/html").documentElement.querySelector("p");cb.parentElement.replaceChild(ib,cb)}else cb.style.textDecoration.includes("none")?cb.style.textDecoration=cb.style.textDecoration.replace("none","underline"):cb.style.textDecoration+=" underline",cb.innerHTML="<u>"+cb.innerHTML.trim()+"</u>"});Ka=Pa.serializeToString(Ka);
y(xa,Ka)},Kma:function(xa,Ka){var Oa=ka(xa.yf.contents);Oa=(new DOMParser).parseFromString(Oa,"text/html").documentElement.querySelector("body");var Pa=Oa.querySelectorAll("p"),Xa=new XMLSerializer;Pa.forEach(function(ab){ab.style.color=Ka});Oa.querySelectorAll("span").forEach(function(ab){ab.setAttribute("style","color:"+Ka)});Oa=Xa.serializeToString(Oa);y(xa,Oa)},cca:function(){return $a},I5:function(xa){return Object(ra.b)(void 0,void 0,void 0,function(){var Ka,Oa,Pa,Xa,ab,cb,ib,lb,ob,rb;return Object(ra.d)(this,
function(tb){switch(tb.label){case 0:return Ka=xa.pageNumber,Oa=xa.newImage,Pa=xa.scaleType,Xa=xa.position,ab=Xa.top,cb=Xa.left,ib=Xa.bottom,lb=Xa.right,ob=Ua.getDocument(),[4,ob.Yd([Ka])];case 1:return rb=tb.da(),Na.postMessage({cmd:"insertImage",pdfFile:rb,pageNumber:Ka,newImage:Oa,scaleType:Pa,topVal:ab,leftVal:cb,bottomVal:ib,rightVal:lb},[]),[2]}})})}}}}]);}).call(this || window)
