(function(){function z(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var A="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,e){a!=Array.prototype&&a!=Object.prototype&&(a[b]=e.value)},B="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function D(){D=function(){};B.Symbol||(B.Symbol=E)}var E=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();
function G(){D();var a=B.Symbol.iterator;a||(a=B.Symbol.iterator=B.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&A(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return H(z(this))}});G=function(){}}function H(a){G();a={next:a};a[B.Symbol.iterator]=function(){return this};return a}function I(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:z(a)}}
function J(a){if(a){for(var b=B,e=["Promise"],h=0;h<e.length-1;h++){var f=e[h];f in b||(b[f]={});b=b[f]}e=e[e.length-1];h=b[e];a=a(h);a!=h&&null!=a&&A(b,e,{configurable:!0,writable:!0,value:a})}}
J(function(a){function b(a){this.w=0;this.K=void 0;this.l=[];var b=this.G();try{a(b.resolve,b.reject)}catch(p){b.reject(p)}}function e(){this.h=null}function h(a){return a instanceof b?a:new b(function(b){b(a)})}if(a)return a;e.prototype.L=function(a){null==this.h&&(this.h=[],this.V());this.h.push(a)};e.prototype.V=function(){var a=this;this.M(function(){a.da()})};var f=B.setTimeout;e.prototype.M=function(a){f(a,0)};e.prototype.da=function(){for(;this.h&&this.h.length;){var a=this.h;this.h=[];for(var b=
0;b<a.length;++b){var f=a[b];a[b]=null;try{f()}catch(d){this.W(d)}}}this.h=null};e.prototype.W=function(a){this.M(function(){throw a;})};b.prototype.G=function(){function a(a){return function(d){f||(f=!0,a.call(b,d))}}var b=this,f=!1;return{resolve:a(this.wa),reject:a(this.J)}};b.prototype.wa=function(a){if(a===this)this.J(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof b)this.xa(a);else{a:switch(typeof a){case "object":var f=null!=a;break a;case "function":f=!0;break a;
default:f=!1}f?this.va(a):this.O(a)}};b.prototype.va=function(a){var b=void 0;try{b=a.then}catch(p){this.J(p);return}"function"==typeof b?this.ya(b,a):this.O(a)};b.prototype.J=function(a){this.T(2,a)};b.prototype.O=function(a){this.T(1,a)};b.prototype.T=function(a,b){if(0!=this.w)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.w);this.w=a;this.K=b;this.ea()};b.prototype.ea=function(){if(null!=this.l){for(var a=0;a<this.l.length;++a)l.L(this.l[a]);this.l=null}};var l=
new e;b.prototype.xa=function(a){var b=this.G();a.C(b.resolve,b.reject)};b.prototype.ya=function(a,b){var f=this.G();try{a.call(b,f.resolve,f.reject)}catch(d){f.reject(d)}};b.prototype.then=function(a,f){function e(c,a){return"function"==typeof c?function(m){try{d(c(m))}catch(n){g(n)}}:a}var d,g,l=new b(function(c,a){d=c;g=a});this.C(e(a,d),e(f,g));return l};b.prototype.catch=function(a){return this.then(void 0,a)};b.prototype.C=function(a,b){function f(){switch(d.w){case 1:a(d.K);break;case 2:b(d.K);
break;default:throw Error("Unexpected state: "+d.w);}}var d=this;null==this.l?l.L(f):this.l.push(f)};b.resolve=h;b.reject=function(a){return new b(function(b,f){f(a)})};b.race=function(a){return new b(function(b,f){for(var d=I(a),e=d.next();!e.done;e=d.next())h(e.value).C(b,f)})};b.all=function(a){var f=I(a),e=f.next();return e.done?h([]):new b(function(a,b){function d(m){return function(n){c[m]=n;k--;0==k&&a(c)}}var c=[],k=0;do c.push(void 0),k++,h(e.value).C(d(c.length-1),b),e=f.next();while(!e.done)})};
return b});function L(){this.u=!1;this.i=null;this.B=void 0;this.f=1;this.N=this.Z=0;this.m=null}function M(a){if(a.u)throw new TypeError("Generator is already running");a.u=!0}L.prototype.v=function(a){this.B=a};L.prototype.A=function(a){this.m={ca:a,na:!0};this.f=this.Z||this.N};L.prototype.return=function(a){this.m={return:a};this.f=this.N};function N(a,b,e){a.f=e;return{value:b}}function O(a){this.b=new L;this.sa=a}
O.prototype.v=function(a){M(this.b);if(this.b.i)return P(this,this.b.i.next,a,this.b.v);this.b.v(a);return Q(this)};function R(a,b){M(a.b);var e=a.b.i;if(e)return P(a,"return"in e?e["return"]:function(a){return{value:a,done:!0}},b,a.b.return);a.b.return(b);return Q(a)}O.prototype.A=function(a){M(this.b);if(this.b.i)return P(this,this.b.i["throw"],a,this.b.v);this.b.A(a);return Q(this)};
function P(a,b,e,h){try{var f=b.call(a.b.i,e);if(!(f instanceof Object))throw new TypeError("Iterator result "+f+" is not an object");if(!f.done)return a.b.u=!1,f;var l=f.value}catch(r){return a.b.i=null,a.b.A(r),Q(a)}a.b.i=null;h.call(a.b,l);return Q(a)}function Q(a){for(;a.b.f;)try{var b=a.sa(a.b);if(b)return a.b.u=!1,{value:b.value,done:!1}}catch(e){a.b.B=void 0,a.b.A(e)}a.b.u=!1;if(a.b.m){b=a.b.m;a.b.m=null;if(b.na)throw b.ca;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function S(a){this.next=function(b){return a.v(b)};this.throw=function(b){return a.A(b)};this.return=function(b){return R(a,b)};G();this[Symbol.iterator]=function(){return this}}function T(a){function b(b){return a.next(b)}function e(b){return a.throw(b)}return new Promise(function(h,f){function l(a){a.done?h(a.value):Promise.resolve(a.value).then(b,e).then(l,f)}l(a.next())})}
(function(a){function b(f){if(e[f])return e[f].o;var l=e[f]={Na:f,oa:!1,o:{}};a[f].call(l.o,l,l.o,b);l.oa=!0;return l.o}self.webpackChunk=function(b,e){for(var f in e)a[f]=e[f];for(;b.length;)h[b.pop()]=1};var e={},h={1:1};b.e=function(a){var f=[];f.push(Promise.resolve().then(function(){h[a]||importScripts(b.p+""+({0:"forge"}[a]||a)+".chunk.js")}));return Promise.all(f)};b.Qa=a;b.Ea=e;b.d=function(a,e,h){b.pa(a,e)||Object.defineProperty(a,e,{enumerable:!0,get:h})};b.r=function(a){D();D();"undefined"!==
typeof Symbol&&Symbol.toStringTag&&(D(),Object.defineProperty(a,Symbol.toStringTag,{value:"Module"}));Object.defineProperty(a,"__esModule",{value:!0})};b.t=function(a,e){e&1&&(a=b(a));if(e&8||e&4&&"object"===typeof a&&a&&a.U)return a;var f=Object.create(null);b.r(f);Object.defineProperty(f,"default",{enumerable:!0,value:a});if(e&2&&"string"!=typeof a)for(var g in a)b.d(f,g,function(b){return a[b]}.bind(null,g));return f};b.n=function(a){var e=a&&a.U?function(){return a["default"]}:function(){return a};
b.d(e,"a",e);return e};b.pa=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};b.p="/core/";return b(b.Va=1)})([function(a,b,e){b.a=function(a,b,l){var f,g,h,d,t,y,c,k,m,n;return T(new S(new O(function(u){if(1==u.f){f=[];for(g=0;16>g;++g)f[g]=g,g<b.length&&(f[g]|=b.charCodeAt(g)),h=l.length+g-16,0<=h&&(f[g]|=l.charCodeAt(h));return N(u,e.e(0).then(e.bind(null,4)),2)}d=u.B;t=d.default;for(var q=[],K=0;16>K;++K)q.push(a.charCodeAt(K));y=q;c=a.slice(16);k=t.g.za(f,y);k.update(t.j.createBuffer(c));
m=k.finish();n=k.P.data;return m?u.return(n):u.return({error:"Bad password or file corrupt"})})))}},function(a,b,e){a.o=e(2)},function(a,b,e){e.r(b);e(3)},function(a,b,e){var h=e(0);self.onmessage=function(a){var b,e,f,p,d;return T(new S(new O(function(g){switch(g.f){case 1:switch(b=a.data.data,e=a.data.password,f=a.data.partName,p=a.data.type,p){case "AES":g.f=2;return;default:g.f=3;return}case 2:return N(g,Object(h.a)(b,e,f),5);case 5:d=g.B;g.f=4;break;case 3:return N(g,Object(h.a)(b,e,f),6);case 6:d=
g.B;g.f=4;break;case 4:self.postMessage(d),g.f=0}})))}}]);}).call(this || window)
