/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[5],{465:function(Ba,va,r){r.r(va);var oa=r(0),ka=r(487),la=r(488),fa;(function(ea){ea[ea.EXTERNAL_XFDF_NOT_REQUESTED=0]="EXTERNAL_XFDF_NOT_REQUESTED";ea[ea.EXTERNAL_XFDF_NOT_AVAILABLE=1]="EXTERNAL_XFDF_NOT_AVAILABLE";ea[ea.EXTERNAL_XFDF_AVAILABLE=2]="EXTERNAL_XFDF_AVAILABLE"})(fa||(fa={}));Ba=function(){function ea(ca){this.aa=ca;this.state=fa.EXTERNAL_XFDF_NOT_REQUESTED}ea.prototype.iea=function(){var ca=this;return function(x,
y,h){return Object(oa.b)(ca,void 0,void 0,function(){var e,b,a,f,n,z,w,da=this,ja;return Object(oa.d)(this,function(aa){switch(aa.label){case 0:if(this.state!==fa.EXTERNAL_XFDF_NOT_REQUESTED)return[3,2];e=this.aa.getDocument().Qs();return[4,this.vca(e)];case 1:b=aa.da(),a=this.p8(b),this.ZI=null!==(ja=null===a||void 0===a?void 0:a.parse())&&void 0!==ja?ja:null,this.state=null===this.ZI?fa.EXTERNAL_XFDF_NOT_AVAILABLE:fa.EXTERNAL_XFDF_AVAILABLE,aa.label=2;case 2:if(this.state===fa.EXTERNAL_XFDF_NOT_AVAILABLE)return h(x),
[2];f=new DOMParser;n=f.parseFromString(x,"text/xml");y.forEach(function(ba){da.merge(n,da.ZI,ba-1)});z=new XMLSerializer;w=z.serializeToString(n);h(w);return[2]}})})}};ea.prototype.VM=function(ca){this.vca=ca};ea.prototype.ue=function(){this.ZI=void 0;this.state=fa.EXTERNAL_XFDF_NOT_REQUESTED};ea.prototype.p8=function(ca){return ca?Array.isArray(ca)?new ka.a(ca):"string"!==typeof ca?null:(new DOMParser).parseFromString(ca,"text/xml").querySelector("xfdf > add")?new ka.a(ca):new la.a(ca):null};ea.prototype.merge=
function(ca,x,y){var h=this;0===y&&(this.Bga(ca,x.zp),this.Dga(ca,x.EI));var e=x.ca[y];e&&(this.Ega(ca,e.xn),this.Gga(ca,e.p0,x.Bw),this.Fga(ca,e.page,y),this.Cga(ca,e.RS));e=this.aa.Qb();if(y===e-1){var b=x.Bw;Object.keys(b).forEach(function(a){b[a].nK||h.SW(ca,a,b[a])})}};ea.prototype.Bga=function(ca,x){null!==x&&(ca=this.Nv(ca),this.Qq(ca,"calculation-order",x))};ea.prototype.Dga=function(ca,x){null!==x&&(ca=this.Nv(ca),this.Qq(ca,"document-actions",x))};ea.prototype.Ega=function(ca,x){var y=this,
h=this.Mv(ca.querySelector("xfdf"),"annots");Object.keys(x).forEach(function(e){y.Qq(h,'[name="'+e+'"]',x[e])})};ea.prototype.Gga=function(ca,x,y){var h=this;if(0!==x.length){var e=this.Nv(ca);x.forEach(function(b){var a=b.getAttribute("field"),f=y[a];f&&(h.SW(ca,a,f),h.Qq(e,"null",b))})}};ea.prototype.SW=function(ca,x,y){var h=this.Nv(ca);null!==y.uC&&this.Qq(h,'ffield [name="'+x+'"]',y.uC);ca=this.Mv(ca.querySelector("xfdf"),"fields");x=x.split(".");this.cM(ca,x,0,y.value);y.nK=!0};ea.prototype.Fga=
function(ca,x,y){null!==x&&(ca=this.Nv(ca),ca=this.Mv(ca,"pages"),this.Qq(ca,'[number="'+(y+1)+'"]',x))};ea.prototype.Cga=function(ca,x){Object.keys(x).forEach(function(y){(y=ca.querySelector('annots [name="'+y+'"]'))&&y.parentElement.removeChild(y)})};ea.prototype.cM=function(ca,x,y,h){if(y===x.length)x=document.createElementNS("","value"),x.textContent=h,this.Qq(ca,"value",x);else{var e=x[y];this.Mv(ca,'[name="'+e+'"]',"field").setAttribute("name",e);ca=ca.querySelectorAll('[name="'+e+'"]');1===
ca.length?this.cM(ca[0],x,y+1,h):(e=this.dba(ca),this.cM(y===x.length-1?e:this.Gna(ca,e),x,y+1,h))}};ea.prototype.dba=function(ca){for(var x=null,y=0;y<ca.length;y++){var h=ca[y];if(0===h.childElementCount||1===h.childElementCount&&"value"===h.children[0].tagName){x=h;break}}return x};ea.prototype.Gna=function(ca,x){for(var y=0;y<ca.length;y++)if(ca[y]!==x)return ca[y];return null};ea.prototype.Qq=function(ca,x,y){x=ca.querySelector(x);null!==x&&ca.removeChild(x);ca.appendChild(y)};ea.prototype.Nv=
function(ca){var x=ca.querySelector("pdf-info");if(null!==x)return x;x=this.Mv(ca.querySelector("xfdf"),"pdf-info");x.setAttribute("xmlns","http://www.pdftron.com/pdfinfo");x.setAttribute("version","2");x.setAttribute("import-version","4");return x};ea.prototype.Mv=function(ca,x,y){var h=ca.querySelector(x);if(null!==h)return h;h=document.createElementNS("",y||x);ca.appendChild(h);return h};return ea}();va["default"]=Ba},476:function(Ba,va){Ba=function(){function r(){}r.prototype.YA=function(oa){var ka=
{zp:null,EI:null,Bw:{},ca:{}};oa=(new DOMParser).parseFromString(oa,"text/xml");ka.zp=oa.querySelector("pdf-info calculation-order");ka.EI=oa.querySelector("pdf-info document-actions");ka.Bw=this.zha(oa);ka.ca=this.Lha(oa);return ka};r.prototype.zha=function(oa){var ka=oa.querySelector("fields");oa=oa.querySelectorAll("pdf-info > ffield");if(null===ka&&null===oa)return{};var la={};this.F5(la,ka);this.D5(la,oa);return la};r.prototype.F5=function(oa,ka){if(null!==ka&&ka.children){for(var la=[],fa=0;fa<
ka.children.length;fa++){var ea=ka.children[fa];la.push({name:ea.getAttribute("name"),element:ea})}for(;0!==la.length;)for(ka=la.shift(),fa=0;fa<ka.element.children.length;fa++)ea=ka.element.children[fa],"value"===ea.tagName?oa[ka.name]={value:ea.textContent,uC:null,nK:!1}:ea.children&&la.push({name:ka.name+"."+ea.getAttribute("name"),element:ea})}};r.prototype.D5=function(oa,ka){ka.forEach(function(la){var fa=la.getAttribute("name");oa[fa]?oa[fa].uC=la:oa[fa]={value:null,uC:la,nK:!1}})};r.prototype.Lha=
function(oa){var ka=this,la={};oa.querySelectorAll("pdf-info widget").forEach(function(fa){var ea=parseInt(fa.getAttribute("page"),10)-1;ka.wD(la,ea);la[ea].p0.push(fa)});oa.querySelectorAll("pdf-info page").forEach(function(fa){var ea=parseInt(fa.getAttribute("number"),10)-1;ka.wD(la,ea);la[ea].page=fa});this.DU(oa).forEach(function(fa){var ea=parseInt(fa.getAttribute("page"),10),ca=fa.getAttribute("name");ka.wD(la,ea);la[ea].xn[ca]=fa});this.oU(oa).forEach(function(fa){var ea=parseInt(fa.getAttribute("page"),
10);fa=fa.textContent;ka.wD(la,ea);la[ea].RS[fa]=!0});return la};r.prototype.wD=function(oa,ka){oa[ka]||(oa[ka]={xn:{},RS:{},p0:[],page:null})};return r}();va.a=Ba},487:function(Ba,va,r){var oa=r(0),ka=r(1);r.n(ka);Ba=function(la){function fa(ea){var ca=la.call(this)||this;ca.Paa=Array.isArray(ea)?ea:[ea];return ca}Object(oa.c)(fa,la);fa.prototype.parse=function(){var ea=this,ca={zp:null,EI:null,Bw:{},ca:{}};this.Paa.forEach(function(x){ca=Object(ka.merge)(ca,ea.YA(x))});return ca};fa.prototype.DU=
function(ea){var ca=[];ea.querySelectorAll("add > *").forEach(function(x){ca.push(x)});ea.querySelectorAll("modify > *").forEach(function(x){ca.push(x)});return ca};fa.prototype.oU=function(ea){return ea.querySelectorAll("delete > *")};return fa}(r(476).a);va.a=Ba},488:function(Ba,va,r){var oa=r(0);Ba=function(ka){function la(fa){var ea=ka.call(this)||this;ea.Qaa=fa;return ea}Object(oa.c)(la,ka);la.prototype.parse=function(){return this.YA(this.Qaa)};la.prototype.DU=function(fa){return fa.querySelectorAll("annots > *")};
la.prototype.oU=function(){return[]};return la}(r(476).a);va.a=Ba}}]);}).call(this || window)
