/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[7],{447:function(Ba,ua,r){r.r(ua);var pa=r(1),ka=r(474),ma=r(475),fa;(function(da){da[da.EXTERNAL_XFDF_NOT_REQUESTED=0]="EXTERNAL_XFDF_NOT_REQUESTED";da[da.EXTERNAL_XFDF_NOT_AVAILABLE=1]="EXTERNAL_XFDF_NOT_AVAILABLE";da[da.EXTERNAL_XFDF_AVAILABLE=2]="EXTERNAL_XFDF_AVAILABLE"})(fa||(fa={}));Ba=function(){function da(z){this.aa=z;this.state=fa.EXTERNAL_XFDF_NOT_REQUESTED}da.prototype.Xca=function(){var z=this;return function(x,y,f){return Object(pa.b)(z,
void 0,void 0,function(){var e,b,a,h,n,aa,w,ea=this,ja;return Object(pa.d)(this,function(ba){switch(ba.label){case 0:if(this.state!==fa.EXTERNAL_XFDF_NOT_REQUESTED)return[3,2];e=this.aa.getDocument().As();return[4,this.kba(e)];case 1:b=ba.ea(),a=this.j7(b),this.xI=null!==(ja=null===a||void 0===a?void 0:a.parse())&&void 0!==ja?ja:null,this.state=null===this.xI?fa.EXTERNAL_XFDF_NOT_AVAILABLE:fa.EXTERNAL_XFDF_AVAILABLE,ba.label=2;case 2:if(this.state===fa.EXTERNAL_XFDF_NOT_AVAILABLE)return f(x),[2];
h=new DOMParser;n=h.parseFromString(x,"text/xml");y.forEach(function(ca){ea.merge(n,ea.xI,ca-1)});aa=new XMLSerializer;w=aa.serializeToString(n);f(w);return[2]}})})}};da.prototype.qM=function(z){this.kba=z};da.prototype.qe=function(){this.xI=void 0;this.state=fa.EXTERNAL_XFDF_NOT_REQUESTED};da.prototype.j7=function(z){return z?Array.isArray(z)?new ka.a(z):"string"!==typeof z?null:(new DOMParser).parseFromString(z,"text/xml").querySelector("xfdf > add")?new ka.a(z):new ma.a(z):null};da.prototype.merge=
function(z,x,y){var f=this;0===y&&(this.pfa(z,x.rp),this.rfa(z,x.eI));var e=x.ca[y];e&&(this.sfa(z,e.sn),this.ufa(z,e.v_,x.hw),this.tfa(z,e.page,y),this.qfa(z,e.fS));e=this.aa.Lb();if(y===e-1){var b=x.hw;Object.keys(b).forEach(function(a){b[a].OJ||f.XV(z,a,b[a])})}};da.prototype.pfa=function(z,x){null!==x&&(z=this.vv(z),this.Hq(z,"calculation-order",x))};da.prototype.rfa=function(z,x){null!==x&&(z=this.vv(z),this.Hq(z,"document-actions",x))};da.prototype.sfa=function(z,x){var y=this,f=this.uv(z.querySelector("xfdf"),
"annots");Object.keys(x).forEach(function(e){y.Hq(f,'[name="'+e+'"]',x[e])})};da.prototype.ufa=function(z,x,y){var f=this;if(0!==x.length){var e=this.vv(z);x.forEach(function(b){var a=b.getAttribute("field"),h=y[a];h&&(f.XV(z,a,h),f.Hq(e,"null",b))})}};da.prototype.XV=function(z,x,y){var f=this.vv(z);null!==y.$B&&this.Hq(f,'ffield [name="'+x+'"]',y.$B);z=this.uv(z.querySelector("xfdf"),"fields");x=x.split(".");this.AL(z,x,0,y.value);y.OJ=!0};da.prototype.tfa=function(z,x,y){null!==x&&(z=this.vv(z),
z=this.uv(z,"pages"),this.Hq(z,'[number="'+(y+1)+'"]',x))};da.prototype.qfa=function(z,x){Object.keys(x).forEach(function(y){(y=z.querySelector('annots [name="'+y+'"]'))&&y.parentElement.removeChild(y)})};da.prototype.AL=function(z,x,y,f){if(y===x.length)x=document.createElementNS("","value"),x.textContent=f,this.Hq(z,"value",x);else{var e=x[y];this.uv(z,'[name="'+e+'"]',"field").setAttribute("name",e);z=z.querySelectorAll('[name="'+e+'"]');1===z.length?this.AL(z[0],x,y+1,f):(e=this.X$(z),this.AL(y===
x.length-1?e:this.gma(z,e),x,y+1,f))}};da.prototype.X$=function(z){for(var x=null,y=0;y<z.length;y++){var f=z[y];if(0===f.childElementCount||1===f.childElementCount&&"value"===f.children[0].tagName){x=f;break}}return x};da.prototype.gma=function(z,x){for(var y=0;y<z.length;y++)if(z[y]!==x)return z[y];return null};da.prototype.Hq=function(z,x,y){x=z.querySelector(x);null!==x&&z.removeChild(x);z.appendChild(y)};da.prototype.vv=function(z){var x=z.querySelector("pdf-info");if(null!==x)return x;x=this.uv(z.querySelector("xfdf"),
"pdf-info");x.setAttribute("xmlns","http://www.pdftron.com/pdfinfo");x.setAttribute("version","2");x.setAttribute("import-version","4");return x};da.prototype.uv=function(z,x,y){var f=z.querySelector(x);if(null!==f)return f;f=document.createElementNS("",y||x);z.appendChild(f);return f};return da}();ua["default"]=Ba},459:function(Ba,ua){Ba=function(){function r(){}r.prototype.BA=function(pa){var ka={rp:null,eI:null,hw:{},ca:{}};pa=(new DOMParser).parseFromString(pa,"text/xml");ka.rp=pa.querySelector("pdf-info calculation-order");
ka.eI=pa.querySelector("pdf-info document-actions");ka.hw=this.mga(pa);ka.ca=this.yga(pa);return ka};r.prototype.mga=function(pa){var ka=pa.querySelector("fields");pa=pa.querySelectorAll("pdf-info > ffield");if(null===ka&&null===pa)return{};var ma={};this.J4(ma,ka);this.H4(ma,pa);return ma};r.prototype.J4=function(pa,ka){if(null!==ka&&ka.children){for(var ma=[],fa=0;fa<ka.children.length;fa++){var da=ka.children[fa];ma.push({name:da.getAttribute("name"),element:da})}for(;0!==ma.length;)for(ka=ma.shift(),
fa=0;fa<ka.element.children.length;fa++)da=ka.element.children[fa],"value"===da.tagName?pa[ka.name]={value:da.textContent,$B:null,OJ:!1}:da.children&&ma.push({name:ka.name+"."+da.getAttribute("name"),element:da})}};r.prototype.H4=function(pa,ka){ka.forEach(function(ma){var fa=ma.getAttribute("name");pa[fa]?pa[fa].$B=ma:pa[fa]={value:null,$B:ma,OJ:!1}})};r.prototype.yga=function(pa){var ka=this,ma={};pa.querySelectorAll("pdf-info widget").forEach(function(fa){var da=parseInt(fa.getAttribute("page"),
10)-1;ka.aD(ma,da);ma[da].v_.push(fa)});pa.querySelectorAll("pdf-info page").forEach(function(fa){var da=parseInt(fa.getAttribute("number"),10)-1;ka.aD(ma,da);ma[da].page=fa});this.MT(pa).forEach(function(fa){var da=parseInt(fa.getAttribute("page"),10),z=fa.getAttribute("name");ka.aD(ma,da);ma[da].sn[z]=fa});this.vT(pa).forEach(function(fa){var da=parseInt(fa.getAttribute("page"),10);fa=fa.textContent;ka.aD(ma,da);ma[da].fS[fa]=!0});return ma};r.prototype.aD=function(pa,ka){pa[ka]||(pa[ka]={sn:{},
fS:{},v_:[],page:null})};return r}();ua.a=Ba},474:function(Ba,ua,r){var pa=r(1),ka=r(0);r.n(ka);Ba=function(ma){function fa(da){var z=ma.call(this)||this;z.J$=Array.isArray(da)?da:[da];return z}Object(pa.c)(fa,ma);fa.prototype.parse=function(){var da=this,z={rp:null,eI:null,hw:{},ca:{}};this.J$.forEach(function(x){z=Object(ka.merge)(z,da.BA(x))});return z};fa.prototype.MT=function(da){var z=[];da.querySelectorAll("add > *").forEach(function(x){z.push(x)});da.querySelectorAll("modify > *").forEach(function(x){z.push(x)});
return z};fa.prototype.vT=function(da){return da.querySelectorAll("delete > *")};return fa}(r(459).a);ua.a=Ba},475:function(Ba,ua,r){var pa=r(1);Ba=function(ka){function ma(fa){var da=ka.call(this)||this;da.K$=fa;return da}Object(pa.c)(ma,ka);ma.prototype.parse=function(){return this.BA(this.K$)};ma.prototype.MT=function(fa){return fa.querySelectorAll("annots > *")};ma.prototype.vT=function(){return[]};return ma}(r(459).a);ua.a=Ba}}]);}).call(this || window)
