/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[0],{432:function(Ba,ua,r){r.r(ua);r.d(ua,"ByteRangeRequest",function(){return aa});var pa=r(1),ka=r(0);r.n(ka);var ma=r(2),fa=r(149);Ba=r(94);var da=r(246),z=r(73),x=r(71),y=r(245),f=r(166);r=r(374);var e=[],b=[],a=window,h=function(){return function(){this.lm=1}}(),n;(function(ea){ea[ea.UNSENT=0]="UNSENT";ea[ea.DONE=4]="DONE"})(n||(n={}));var aa=function(){function ea(ja,ba,ca,ia){var ha=this;this.url=ja;this.range=ba;this.df=ca;
this.withCredentials=ia;this.q2=n;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);a.Uint8Array&&(this.request.responseType="arraybuffer");ia&&(this.request.withCredentials=ia);w.DISABLE_RANGE_HEADER||(Object(ka.isUndefined)(ba.stop)?this.request.setRequestHeader("Range","bytes="+ba.start):this.request.setRequestHeader("Range",["bytes=",ba.start,"-",ba.stop-1].join("")));ca&&Object.keys(ca).forEach(function(la){ha.request.setRequestHeader(la,ca[la])});this.request.overrideMimeType?
this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=y.a.NOT_STARTED}ea.prototype.start=function(ja){var ba=this,ca=this.request;ca.onreadystatechange=function(){if(ba.aborted)return ba.status=y.a.ABORTED,ja({code:y.a.ABORTED});if(this.readyState===ba.q2.DONE){ba.BC();var ia=0===window.document.URL.indexOf("file:///");200===ca.status||206===ca.status||ia&&0===ca.status?(ia=a.bU(this),ba.bN(ia,ja)):(ba.status=
y.a.ERROR,ja({code:ba.status,status:ba.status}))}};this.request.send(null);this.status=y.a.STARTED};ea.prototype.bN=function(ja,ba){this.status=y.a.SUCCESS;if(ba)return ba(!1,ja)};ea.prototype.abort=function(){this.BC();this.aborted=!0;this.request.abort()};ea.prototype.BC=function(){var ja=Object(f.c)(this.url,this.range,b);-1!==ja&&b.splice(ja,1);if(0<e.length){ja=e.shift();var ba=new ea(ja.url,ja.range,this.df,this.withCredentials);ja.request=ba;b.push(ja);ba.start(Object(f.d)(ja))}};ea.prototype.extend=
function(ja){var ba=Object.assign({},this,ja.prototype);ba.constructor=ja;return ba};return ea}(),w=function(ea){function ja(ba,ca,ia,ha,la){ia=ea.call(this,ba,ia,ha)||this;ia.pm={};ia.dB=ca;ia.url=ba;ia.DISABLE_RANGE_HEADER=!1;ia.Vx=aa;ia.ZN=3;ia.df=la||{};return ia}Object(pa.c)(ja,ea);ja.prototype.Ov=function(ba,ca,ia){var ha=-1===ba.indexOf("?")?"?":"&";switch(ia){case !1:case x.a.NEVER_CACHE:ba=ba+ha+"_="+Object(ka.uniqueId)();break;case !0:case x.a.CACHE:ba=ba+ha+"_="+ca.start+","+(Object(ka.isUndefined)(ca.stop)?
"":ca.stop)}return ba};ja.prototype.SR=function(ba,ca,ia,ha){void 0===ia&&(ia={});return new this.Vx(ba,ca,ia,ha)};ja.prototype.z$=function(ba,ca,ia,ha,la){for(var na=0;na<e.length;na++)if(Object(ka.isEqual)(e[na].range,ca)&&Object(ka.isEqual)(e[na].url,ba))return e[na].Og.push(ha),e[na].GD++,null;for(na=0;na<b.length;na++)if(Object(ka.isEqual)(b[na].range,ca)&&Object(ka.isEqual)(b[na].url,ba))return b[na].Og.push(ha),b[na].GD++,null;ia={url:ba,range:ca,dB:ia,Og:[ha],GD:1};if(0===e.length&&b.length<
this.ZN)return b.push(ia),ia.request=this.SR(ba,ca,la,this.withCredentials),ia;e.push(ia);return null};ja.prototype.io=function(ba,ca,ia){var ha=this.Ov(ba,ca,this.dB);(ba=this.z$(ha,ca,this.dB,ia,this.df))&&ba.request.start(Object(f.d)(ba));return function(){var la=Object(f.c)(ha,ca,b);if(-1!==la){var na=--b[la].GD;0===na&&b[la].request&&b[la].request.abort()}else la=Object(f.c)(ha,ca,e),-1!==la&&(na=--e[la].GD,0===na&&e.splice(la,1))}};ja.prototype.AT=function(){return{start:-fa.a}};ja.prototype.fda=
function(){var ba=-(fa.a+fa.e);return{start:ba-fa.d,end:ba}};ja.prototype.qt=function(ba){var ca=this;this.jB=!0;var ia=fa.a;this.io(this.url,this.AT(),function(ha,la,na){function qa(){var ra=ca.Zd.wT();ca.io(ca.url,ra,function(ta,va){if(ta)return Object(ma.j)("Error loading central directory: "+ta),ba(ta);va=Object(z.a)(va);if(va.length!==ra.stop-ra.start)return ba("Invalid XOD file: Zip central directory data is wrong size! Should be "+(ra.stop-ra.start)+" but is "+va.length);ca.Zd.uX(va);ca.GH=
!0;ca.jB=!1;return ba(!1)})}if(ha)return Object(ma.j)("Error loading end header: "+ha),ba(ha,la,na);la=Object(z.a)(la);if(la.length!==ia)return ba("Invalid XOD file: Zip end header data is wrong size!");try{ca.Zd=new da.a(la)}catch(ra){return ba(ra)}ca.Zd.Jea?ca.io(ca.url,ca.fda(),function(ra,ta){if(ra)return Object(ma.j)("Error loading zip64 header: "+ra),ba(ra);ta=Object(z.a)(ta);ca.Zd.bfa(ta);qa()}):qa()})};ja.prototype.ZT=function(ba){ba(Object.keys(this.Zd.Hn))};ja.prototype.DL=function(ba,ca){var ia=
this;if(this.Zd.HR(ba)){var ha=this.Zd.vC(ba);if(ha in this.pm){var la=this.Zh[ba];la.Yr=this.pm[ha];la.Yr.lm++;la.cancel=la.Yr.cancel}else{var na=this.Zd.rba(ba),qa=this.io(this.url,na,function(ta,va){ta?(Object(ma.j)('Error loading part "'+ba+'": '+ta),ia.io(ia.url,na,function(oa,wa){if(oa)return ca(oa,ba);ia.yX(wa,na,ha,ba,ca)})):ia.yX(va,na,ha,ba,ca)}),ra=this.Zh[ba];ra&&(ra.DZ=!0,ra.cancel=function(){ra.Yr.lm--;0===ra.Yr.lm&&(qa(),delete ia.pm[ha])},this.pm[ha]=new h(ha),ra.Yr=this.pm[ha],ra.Yr.cancel=
ra.cancel)}}else delete this.Zh[ba],ca(Error('File not found: "'+ba+'"'),ba)};ja.prototype.yX=function(ba,ca,ia,ha,la){if(ba.length!==ca.stop-ca.start)la(Error("Part data is wrong size!"),ha);else{do{if(!this.pm[ia])return;ha=this.pm[ia].lm;for(var na=ca.Iq.length,qa=0;qa<na;++qa){var ra=ca.Iq[qa];la(!1,ra.Eq,ba["string"===typeof ba?"substring":"subarray"](ra.start,ra.stop),this.Zd.$U(ra.Eq));ra.Eq in this.Zh&&delete this.Zh[ra.Eq]}}while(ha!==this.pm[ia].lm);delete this.pm[ia]}};ja.DISABLE_RANGE_HEADER=
!1;ja.ZN=3;return ja}(Ba.a);(function(ea){function ja(ba,ca,ia){var ha=ea.call(this)||this,la;for(la in ba)ha[la]=ba[la];ha.dqa=ba;ha.startOffset=ca;ha.endOffset=ia;ha.SR=function(na,qa,ra,ta){Object(ka.isUndefined)(qa.stop)?(qa.start+=ha.endOffset,qa.stop=ha.endOffset):(qa.start+=ha.startOffset,qa.stop+=ha.startOffset);na=ha.Ov(ha.url,qa,ha.dB);return new ba.Vx(na,qa,ra,ta)};return ha}Object(pa.c)(ja,ea);return ja})(w);Object(r.a)(w);Object(r.b)(w);ua["default"]=w}}]);}).call(this || window)
