/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[10],{464:function(Ba,va,r){function oa(ba){ba.Ha();ba.advance();var ia=ba.current.textContent;ba.Xa();return ia}function ka(ba){var ia=[];for(ba.Ha();ba.advance();){var ha=ba.La();"field"===ha?ia.push(String(ba.ga("name"))):Object(a.j)("unrecognised field list element: "+ha)}ba.Xa();return ia}function la(ba,ia){return ia?"false"!==ba:"true"===ba}function fa(ba,ia){var ha=ba.La();switch(ha){case "javascript":return{name:"JavaScript",
javascript:ba.current.textContent};case "uri":return{name:"URI",uri:ba.ga("uri")};case "goto":ha=null;ba.Ha();if(ba.advance()){var ma=ba.ga("fit");ha={page:ba.ga("page"),fit:ma};if("0"===ha.page)Object(a.j)("null page encountered in dest");else switch(ia=ia(Number(ha.page)),ma){case "Fit":case "FitB":break;case "FitH":case "FitBH":ha.top=ia.ra({x:0,y:ba.ga("top")||0}).y;break;case "FitV":case "FitBV":ha.left=ia.ra({x:ba.ga("left")||0,y:0}).x;break;case "FitR":ma=ia.ra({x:ba.ga("left")||0,y:ba.ga("top")||
0});ia=ia.ra({x:ba.ga("right")||0,y:ba.ga("bottom")||0});ia=new z.d(ma.x,ma.y,ia.x,ia.y);ha.top=ia.y1;ha.left=ia.x1;ha.bottom=ia.y2;ha.right=ia.x2;break;case "XYZ":ma=ia.ra({x:ba.ga("left")||0,y:ba.ga("top")||0});ha.top=ma.y;ha.left=ma.x;ha.zoom=ba.ga("zoom")||0;break;default:Object(a.j)("unknown dest fit: "+ma)}ha={name:"GoTo",dest:ha}}else Object(a.j)("missing dest in GoTo action");ba.Xa();return ha;case "submit-form":ha={name:"SubmitForm",url:ba.ga("url"),format:ba.ga("format"),method:ba.ga("method")||
"POST",exclude:la(ba.ga("exclude"),!1)};ia=ba.ga("flags");ha.flags=ia?ia.split(" "):[];for(ba.Ha();ba.advance();)switch(ia=ba.La(),ia){case "fields":ha.fields=ka(ba);break;default:Object(a.j)("unrecognised submit-form child: "+ia)}ba.Xa();return ha;case "reset-form":ha={name:"ResetForm",exclude:la(ba.ga("exclude"),!1)};for(ba.Ha();ba.advance();)switch(ia=ba.La(),ia){case "fields":ha.fields=ka(ba);break;default:Object(a.j)("unrecognised reset-form child: "+ia)}ba.Xa();return ha;case "hide":ha={name:"Hide",
hide:la(ba.ga("hide"),!0)};for(ba.Ha();ba.advance();)switch(ia=ba.La(),ia){case "fields":ha.fields=ka(ba);break;default:Object(a.j)("unrecognised hide child: "+ia)}ba.Xa();return ha;case "named":return{name:"Named",action:ba.ga("name")};default:Object(a.j)("Encountered unexpected action type: "+ha)}return null}function ea(ba,ia,ha){var ma={};for(ba.Ha();ba.advance();){var na=ba.La();switch(na){case "action":na=ba.ga("trigger");if(ia?-1!==ia.indexOf(na):1){ma[na]=[];for(ba.Ha();ba.advance();){var sa=
fa(ba,ha);Object(f.isNull)(sa)||ma[na].push(sa)}ba.Xa()}else Object(a.j)("encountered unexpected trigger on field: "+na);break;default:Object(a.j)("encountered unknown action child: "+na)}}ba.Xa();return ma}function ca(ba){return new w.a(ba.ga("r")||0,ba.ga("g")||0,ba.ga("b")||0,ba.ga("a")||1)}function x(ba,ia){var ha=ba.ga("name"),ma=ba.ga("type")||"Type1",na=ba.ga("size"),sa=ia.ra({x:0,y:0});na=ia.ra({x:Number(na),y:0});ia=sa.x-na.x;sa=sa.y-na.y;ha={name:ha,type:ma,size:Math.sqrt(ia*ia+sa*sa)||
0,strokeColor:[0,0,0],fillColor:[0,0,0]};for(ba.Ha();ba.advance();)switch(ma=ba.La(),ma){case "stroke-color":ha.strokeColor=ca(ba);break;case "fill-color":ha.fillColor=ca(ba);break;default:Object(a.j)("unrecognised font child: "+ma)}ba.Xa();return ha}function y(ba){var ia=[];for(ba.Ha();ba.advance();){var ha=ba.La();switch(ha){case "option":ha=ia;var ma=ha.push;var na=ba;na={value:na.ga("value"),displayValue:na.ga("display-value")||void 0};ma.call(ha,na);break;default:Object(a.j)("unrecognised options child: "+
ha)}}ba.Xa();return ia}function h(ba,ia){var ha=ba.ga("name"),ma={type:ba.ga("type"),quadding:ba.ga("quadding")||"Left-justified",maxLen:ba.ga("max-len")||-1},na=ba.ga("flags");Object(f.isString)(na)&&(ma.flags=na.split(" "));for(ba.Ha();ba.advance();)switch(na=ba.La(),na){case "actions":ma.actions=ea(ba,["C","F","K","V"],function(){return ia});break;case "default-value":ma.defaultValue=oa(ba);break;case "font":ma.font=x(ba,ia);break;case "options":ma.options=y(ba);break;default:Object(a.j)("unknown field child: "+
na)}ba.Xa();return new window.Annotations.ha.pa(ha,ma)}function e(ba,ia){switch(ba.type){case "Tx":try{if(Object(ja.c)(ba.actions))return new n.a.DatePickerWidgetAnnotation(ba,ia)}catch(ha){Object(a.j)(ha)}return new n.a.TextWidgetAnnotation(ba,ia);case "Ch":return ba.flags.get(aa.WidgetFlags.COMBO)?new n.a.ChoiceWidgetAnnotation(ba,ia):new n.a.ListWidgetAnnotation(ba,ia);case "Btn":return ba.flags.get(aa.WidgetFlags.PUSH_BUTTON)?new n.a.PushButtonWidgetAnnotation(ba,ia):ba.flags.get(aa.WidgetFlags.RADIO)?
new n.a.RadioButtonWidgetAnnotation(ba,ia):new n.a.CheckButtonWidgetAnnotation(ba,ia);case "Sig":return new n.a.SignatureWidgetAnnotation(ba,ia);default:Object(a.j)("Unrecognised field type: "+ba.type)}return null}function b(ba,ia,ha,ma){var na=[],sa={};ba.Ha();var qa=[],ra={},ua=[];Object(da.a)(function(){if(ba.advance()){var pa=ba.La();switch(pa){case "calculation-order":qa="calculation-order"===ba.La()?ka(ba):[];break;case "document-actions":ra=ea(ba,["Init","Open"],ia);break;case "pages":pa=[];
for(ba.Ha();ba.advance();){var wa=ba.La();switch(wa){case "page":wa=pa;var Aa=wa.push,Ha=ba,Ia=ia,Da={number:Ha.ga("number")};for(Ha.Ha();Ha.advance();){var Ja=Ha.La();switch(Ja){case "actions":Da.actions=ea(Ha,["O","C"],Ia);break;default:Object(a.j)("unrecognised page child: "+Ja)}}Ha.Xa();Aa.call(wa,Da);break;default:Object(a.j)("unrecognised page child: "+wa)}}ba.Xa();ua=pa;break;case "field":wa=h(ba,ia(1));sa[wa.name]=wa;break;case "widget":pa={border:{style:"Solid",width:1},backgroundColor:[],
fieldName:ba.ga("field"),page:ba.ga("page"),index:ba.ga("index")||0,rotation:ba.ga("rotation")||0,flags:[],isImporting:!0};(wa=ba.ga("appearance"))&&(pa.appearance=wa);(wa=ba.ga("flags"))&&(pa.flags=wa.split(" "));for(ba.Ha();ba.advance();)switch(wa=ba.La(),wa){case "rect":Aa=ba;Ha=ia(Number(pa.page));wa=Ha.ra({x:Aa.ga("x1")||0,y:Aa.ga("y1")||0});Aa=Ha.ra({x:Aa.ga("x2")||0,y:Aa.ga("y2")||0});wa=new z.d(wa.x,wa.y,Aa.x,Aa.y);wa.normalize();pa.rect={x1:wa.x1,y1:wa.y1,x2:wa.x2,y2:wa.y2};break;case "border":wa=
ba;Aa={style:wa.ga("style")||"Solid",width:wa.ga("width")||1,color:[0,0,0]};for(wa.Ha();wa.advance();)switch(Ha=wa.La(),Ha){case "color":Aa.color=ca(wa);break;default:Object(a.j)("unrecognised border child: "+Ha)}wa.Xa();pa.border=Aa;break;case "background-color":pa.backgroundColor=ca(ba);break;case "actions":pa.actions=ea(ba,"E X D U Fo Bl PO PC PV PI".split(" "),ia);break;case "appearances":wa=ba;Aa=Object(ja.b)(pa,"appearances");for(wa.Ha();wa.advance();)if(Ha=wa.La(),"appearance"===Ha){Ha=wa.ga("name");
Ia=Object(ja.b)(Aa,Ha);Ha=wa;for(Ha.Ha();Ha.advance();)switch(Da=Ha.La(),Da){case "Normal":Object(ja.b)(Ia,"Normal").data=Ha.current.textContent;break;default:Object(a.j)("unexpected appearance state: ",Da)}Ha.Xa()}else Object(a.j)("unexpected appearances child: "+Ha);wa.Xa();break;case "extra":wa=ba;Aa=ia;Ha={};for(wa.Ha();wa.advance();)switch(Ia=wa.La(),Ia){case "font":Ha.font=x(wa,Aa(1));break;default:Object(a.j)("unrecognised extra child: "+Ia)}wa.Xa();wa=Ha;wa.font&&(pa.font=wa.font);break;case "captions":Aa=
ba;wa={};(Ha=Aa.ga("Normal"))&&(wa.Normal=Ha);(Ha=Aa.ga("Rollover"))&&(wa.Rollover=Ha);(Aa=Aa.ga("Down"))&&(wa.Down=Aa);pa.captions=wa;break;default:Object(a.j)("unrecognised widget child: "+wa)}ba.Xa();(wa=sa[pa.fieldName])?(pa=e(wa,pa),na.push(pa)):Object(a.j)("ignoring widget with no corresponding field data: "+pa.fieldName);break;default:Object(a.j)("Unknown element encountered in PDFInfo: "+pa)}return!0}return!1},function(){ba.Xa();ha({calculationOrder:qa,widgets:na,fields:sa,documentActions:ra,
pages:ua,custom:[]})},ma)}r.r(va);r.d(va,"parse",function(){return b});var a=r(2),f=r(1);r.n(f);var n=r(120),z=r(4),w=r(7),da=r(20),ja=r(106),aa=r(17)}}]);}).call(this || window)
