/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[12],{446:function(Ba,ua,r){function pa(ca){ca.Ga();ca.advance();var ia=ca.current.textContent;ca.Wa();return ia}function ka(ca){var ia=[];for(ca.Ga();ca.advance();){var ha=ca.Ka();"field"===ha?ia.push(String(ca.ga("name"))):Object(a.j)("unrecognised field list element: "+ha)}ca.Wa();return ia}function ma(ca,ia){return ia?"false"!==ca:"true"===ca}function fa(ca,ia){var ha=ca.Ka();switch(ha){case "javascript":return{name:"JavaScript",
javascript:ca.current.textContent};case "uri":return{name:"URI",uri:ca.ga("uri")};case "goto":ha=null;ca.Ga();if(ca.advance()){var la=ca.ga("fit");ha={page:ca.ga("page"),fit:la};if("0"===ha.page)Object(a.j)("null page encountered in dest");else switch(ia=ia(Number(ha.page)),la){case "Fit":case "FitB":break;case "FitH":case "FitBH":ha.top=ia.pa({x:0,y:ca.ga("top")||0}).y;break;case "FitV":case "FitBV":ha.left=ia.pa({x:ca.ga("left")||0,y:0}).x;break;case "FitR":la=ia.pa({x:ca.ga("left")||0,y:ca.ga("top")||
0});ia=ia.pa({x:ca.ga("right")||0,y:ca.ga("bottom")||0});ia=new aa.d(la.x,la.y,ia.x,ia.y);ha.top=ia.y1;ha.left=ia.x1;ha.bottom=ia.y2;ha.right=ia.x2;break;case "XYZ":la=ia.pa({x:ca.ga("left")||0,y:ca.ga("top")||0});ha.top=la.y;ha.left=la.x;ha.zoom=ca.ga("zoom")||0;break;default:Object(a.j)("unknown dest fit: "+la)}ha={name:"GoTo",dest:ha}}else Object(a.j)("missing dest in GoTo action");ca.Wa();return ha;case "submit-form":ha={name:"SubmitForm",url:ca.ga("url"),format:ca.ga("format"),method:ca.ga("method")||
"POST",exclude:ma(ca.ga("exclude"),!1)};ia=ca.ga("flags");ha.flags=ia?ia.split(" "):[];for(ca.Ga();ca.advance();)switch(ia=ca.Ka(),ia){case "fields":ha.fields=ka(ca);break;default:Object(a.j)("unrecognised submit-form child: "+ia)}ca.Wa();return ha;case "reset-form":ha={name:"ResetForm",exclude:ma(ca.ga("exclude"),!1)};for(ca.Ga();ca.advance();)switch(ia=ca.Ka(),ia){case "fields":ha.fields=ka(ca);break;default:Object(a.j)("unrecognised reset-form child: "+ia)}ca.Wa();return ha;case "hide":ha={name:"Hide",
hide:ma(ca.ga("hide"),!0)};for(ca.Ga();ca.advance();)switch(ia=ca.Ka(),ia){case "fields":ha.fields=ka(ca);break;default:Object(a.j)("unrecognised hide child: "+ia)}ca.Wa();return ha;case "named":return{name:"Named",action:ca.ga("name")};default:Object(a.j)("Encountered unexpected action type: "+ha)}return null}function da(ca,ia,ha){var la={};for(ca.Ga();ca.advance();){var na=ca.Ka();switch(na){case "action":na=ca.ga("trigger");if(ia?-1!==ia.indexOf(na):1){la[na]=[];for(ca.Ga();ca.advance();){var qa=
fa(ca,ha);Object(h.isNull)(qa)||la[na].push(qa)}ca.Wa()}else Object(a.j)("encountered unexpected trigger on field: "+na);break;default:Object(a.j)("encountered unknown action child: "+na)}}ca.Wa();return la}function z(ca){return new w.a(ca.ga("r")||0,ca.ga("g")||0,ca.ga("b")||0,ca.ga("a")||1)}function x(ca,ia){var ha=ca.ga("name"),la=ca.ga("type")||"Type1",na=ca.ga("size"),qa=ia.pa({x:0,y:0});na=ia.pa({x:Number(na),y:0});ia=qa.x-na.x;qa=qa.y-na.y;ha={name:ha,type:la,size:Math.sqrt(ia*ia+qa*qa)||0,
strokeColor:[0,0,0],fillColor:[0,0,0]};for(ca.Ga();ca.advance();)switch(la=ca.Ka(),la){case "stroke-color":ha.strokeColor=z(ca);break;case "fill-color":ha.fillColor=z(ca);break;default:Object(a.j)("unrecognised font child: "+la)}ca.Wa();return ha}function y(ca){var ia=[];for(ca.Ga();ca.advance();){var ha=ca.Ka();switch(ha){case "option":ha=ia;var la=ha.push;var na=ca;na={value:na.ga("value"),displayValue:na.ga("display-value")||void 0};la.call(ha,na);break;default:Object(a.j)("unrecognised options child: "+
ha)}}ca.Wa();return ia}function f(ca,ia){var ha=ca.ga("name"),la={type:ca.ga("type"),quadding:ca.ga("quadding")||"Left-justified",maxLen:ca.ga("max-len")||-1},na=ca.ga("flags");Object(h.isString)(na)&&(la.flags=na.split(" "));for(ca.Ga();ca.advance();)switch(na=ca.Ka(),na){case "actions":la.actions=da(ca,["C","F","K","V"],function(){return ia});break;case "default-value":la.defaultValue=pa(ca);break;case "font":la.font=x(ca,ia);break;case "options":la.options=y(ca);break;default:Object(a.j)("unknown field child: "+
na)}ca.Wa();return new window.Annotations.ha.na(ha,la)}function e(ca,ia){switch(ca.type){case "Tx":try{if(Object(ja.c)(ca.actions))return new n.a.DatePickerWidgetAnnotation(ca,ia)}catch(ha){Object(a.j)(ha)}return new n.a.TextWidgetAnnotation(ca,ia);case "Ch":return ca.flags.get(ba.WidgetFlags.COMBO)?new n.a.ChoiceWidgetAnnotation(ca,ia):new n.a.ListWidgetAnnotation(ca,ia);case "Btn":return ca.flags.get(ba.WidgetFlags.PUSH_BUTTON)?new n.a.PushButtonWidgetAnnotation(ca,ia):ca.flags.get(ba.WidgetFlags.RADIO)?
new n.a.RadioButtonWidgetAnnotation(ca,ia):new n.a.CheckButtonWidgetAnnotation(ca,ia);case "Sig":return new n.a.SignatureWidgetAnnotation(ca,ia);default:Object(a.j)("Unrecognised field type: "+ca.type)}return null}function b(ca,ia,ha,la){var na=[],qa={};ca.Ga();var ra=[],ta={},va=[];Object(ea.a)(function(){if(ca.advance()){var oa=ca.Ka();switch(oa){case "calculation-order":ra="calculation-order"===ca.Ka()?ka(ca):[];break;case "document-actions":ta=da(ca,["Init","Open"],ia);break;case "pages":oa=[];
for(ca.Ga();ca.advance();){var wa=ca.Ka();switch(wa){case "page":wa=oa;var Da=wa.push,Ha=ca,La=ia,Ca={number:Ha.ga("number")};for(Ha.Ga();Ha.advance();){var Ka=Ha.Ka();switch(Ka){case "actions":Ca.actions=da(Ha,["O","C"],La);break;default:Object(a.j)("unrecognised page child: "+Ka)}}Ha.Wa();Da.call(wa,Ca);break;default:Object(a.j)("unrecognised page child: "+wa)}}ca.Wa();va=oa;break;case "field":wa=f(ca,ia(1));qa[wa.name]=wa;break;case "widget":oa={border:{style:"Solid",width:1},backgroundColor:[],
fieldName:ca.ga("field"),page:ca.ga("page"),index:ca.ga("index")||0,rotation:ca.ga("rotation")||0,flags:[],isImporting:!0};(wa=ca.ga("appearance"))&&(oa.appearance=wa);(wa=ca.ga("flags"))&&(oa.flags=wa.split(" "));for(ca.Ga();ca.advance();)switch(wa=ca.Ka(),wa){case "rect":Da=ca;Ha=ia(Number(oa.page));wa=Ha.pa({x:Da.ga("x1")||0,y:Da.ga("y1")||0});Da=Ha.pa({x:Da.ga("x2")||0,y:Da.ga("y2")||0});wa=new aa.d(wa.x,wa.y,Da.x,Da.y);wa.normalize();oa.rect={x1:wa.x1,y1:wa.y1,x2:wa.x2,y2:wa.y2};break;case "border":wa=
ca;Da={style:wa.ga("style")||"Solid",width:wa.ga("width")||1,color:[0,0,0]};for(wa.Ga();wa.advance();)switch(Ha=wa.Ka(),Ha){case "color":Da.color=z(wa);break;default:Object(a.j)("unrecognised border child: "+Ha)}wa.Wa();oa.border=Da;break;case "background-color":oa.backgroundColor=z(ca);break;case "actions":oa.actions=da(ca,"E X D U Fo Bl PO PC PV PI".split(" "),ia);break;case "appearances":wa=ca;Da=Object(ja.b)(oa,"appearances");for(wa.Ga();wa.advance();)if(Ha=wa.Ka(),"appearance"===Ha){Ha=wa.ga("name");
La=Object(ja.b)(Da,Ha);Ha=wa;for(Ha.Ga();Ha.advance();)switch(Ca=Ha.Ka(),Ca){case "Normal":Object(ja.b)(La,"Normal").data=Ha.current.textContent;break;default:Object(a.j)("unexpected appearance state: ",Ca)}Ha.Wa()}else Object(a.j)("unexpected appearances child: "+Ha);wa.Wa();break;case "extra":wa=ca;Da=ia;Ha={};for(wa.Ga();wa.advance();)switch(La=wa.Ka(),La){case "font":Ha.font=x(wa,Da(1));break;default:Object(a.j)("unrecognised extra child: "+La)}wa.Wa();wa=Ha;wa.font&&(oa.font=wa.font);break;case "captions":Da=
ca;wa={};(Ha=Da.ga("Normal"))&&(wa.Normal=Ha);(Ha=Da.ga("Rollover"))&&(wa.Rollover=Ha);(Da=Da.ga("Down"))&&(wa.Down=Da);oa.captions=wa;break;default:Object(a.j)("unrecognised widget child: "+wa)}ca.Wa();(wa=qa[oa.fieldName])?(oa=e(wa,oa),na.push(oa)):Object(a.j)("ignoring widget with no corresponding field data: "+oa.fieldName);break;default:Object(a.j)("Unknown element encountered in PDFInfo: "+oa)}return!0}return!1},function(){ca.Wa();ha({calculationOrder:ra,widgets:na,fields:qa,documentActions:ta,
pages:va,custom:[]})},la)}r.r(ua);r.d(ua,"parse",function(){return b});var a=r(2),h=r(0);r.n(h);var n=r(117),aa=r(4),w=r(7),ea=r(20),ja=r(102),ba=r(17)}}]);}).call(this || window)
