/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[11],{467:function(Ba,va,r){r.r(va);var oa=r(477),ka=r(119),la=r(41),fa=r(76);Ba=function(){function ea(){this.rb=this.xe=this.Sb=this.jc=null;this.Me=!1}ea.prototype.clear=function(){Object(la.b)(this.jc);this.Sb="";Object(la.b)(this.xe);Object(la.b)(this.rb);this.Me=!1};ea.prototype.ld=function(){this.jc=[];this.xe=[];this.rb=[];this.Me=!1};ea.prototype.CA=function(ca){for(var x="",y=0,h,e,b;y<ca.length;)h=ca.charCodeAt(y),9===
h?(x+=String.fromCharCode(10),y++):128>h?(x+=String.fromCharCode(h),y++):191<h&&224>h?(e=ca.charCodeAt(y+1),x+=String.fromCharCode((h&31)<<6|e&63),y+=2):(e=ca.charCodeAt(y+1),b=ca.charCodeAt(y+2),x+=String.fromCharCode((h&15)<<12|(e&63)<<6|b&63),y+=3);return x};ea.prototype.initData=function(ca){this.jc=[];this.xe=[];this.rb=[];this.Me=!1;try{var x=new fa.a(ca);this.Sb="";x.Ha();if(!x.advance())return;var y=x.current.textContent;this.Sb=y=this.CA(y);Object(la.b)(this.xe);x.advance();y=x.current.textContent;
for(var h=y.split(","),e=Object(ka.a)(h);e.lm();){var b=e.current;try{var a=parseInt(b.trim(),10);this.xe.push(a)}catch(aa){}}Object(la.b)(this.jc);x.advance();y=x.current.textContent;h=y.split(",");for(var f=Object(ka.a)(h);f.lm();){b=f.current;try{a=parseFloat(b.trim()),this.jc.push(a)}catch(aa){}}Object(la.b)(this.rb);x.advance();y=x.current.textContent;h=y.split(",");ca=[];x=[];y=0;for(var n=Object(ka.a)(h);n.lm();){b=n.current;switch(b){case "Q":y=1;break;case "R":y=2;break;case "S":y=3;break;
default:y=0}if(y)ca.push(0),x.push(y);else try{a=parseFloat(b.trim()),ca.push(a),x.push(y)}catch(aa){return}}y=0;var z=ca.length;e=n=b=h=void 0;for(var w=f=0,da=0;da<z;){var ja=x[da];if(0<ja)y=ja,++da,3===y&&(f=ca[da],w=ca[da+1],da+=2);else if(1===y)for(a=0;8>a;++a)this.rb.push(ca[da++]);else 2===y?(h=ca[da++],b=ca[da++],n=ca[da++],e=ca[da++],this.rb.push(h),this.rb.push(b),this.rb.push(n),this.rb.push(b),this.rb.push(n),this.rb.push(e),this.rb.push(h),this.rb.push(e)):3===y&&(h=ca[da++],b=f,n=ca[da++],
e=w,this.rb.push(h),this.rb.push(b),this.rb.push(n),this.rb.push(b),this.rb.push(n),this.rb.push(e),this.rb.push(h),this.rb.push(e))}}catch(aa){return}this.Sb.length&&this.Sb.length===this.xe.length&&8*this.Sb.length===this.rb.length&&(this.Me=!0)};ea.prototype.ready=function(){return this.Me};ea.prototype.Qw=function(){var ca=new oa.a;if(!this.jc.length)return ca.ih(this.jc,-1,this.Sb,this.rb,0),ca;ca.ih(this.jc,1,this.Sb,this.rb,1);return ca};ea.prototype.lf=function(){return this.rb};ea.prototype.getData=
function(){return{m_Struct:this.jc,m_Str:this.Sb,m_Offsets:this.xe,m_Quads:this.rb,m_Ready:this.Me}};return ea}();va["default"]=Ba},477:function(Ba,va,r){var oa=r(88),ka=r(52),la=r(490);Ba=function(){function fa(){this.ee=0;this.pb=this.Ba=this.af=null;this.Pc=0;this.de=null}fa.prototype.ld=function(){this.ee=-1;this.Pc=0;this.de=[]};fa.prototype.ih=function(ea,ca,x,y,h){this.ee=ca;this.Pc=h;this.de=[];this.af=ea;this.Ba=x;this.pb=y};fa.prototype.Gc=function(ea){return this.ee===ea.ee};fa.prototype.hk=
function(){return Math.abs(this.af[this.ee])};fa.prototype.gm=function(){return 0<this.af[this.ee]};fa.prototype.ah=function(){var ea=this.gm()?6:10,ca=new la.a;ca.ih(this.af,this.ee+ea,this.ee,this.Ba,this.pb,1);return ca};fa.prototype.jV=function(ea){if(0>ea||ea>=this.hk())return ea=new la.a,ea.ih(this.af,-1,-1,this.Ba,this.pb,0),ea;var ca=this.gm()?6:10,x=this.gm()?5:11,y=new la.a;y.ih(this.af,this.ee+ca+x*ea,this.ee,this.Ba,this.pb,1+ea);return y};fa.prototype.Wn=function(){var ea=this.ee+parseInt(this.af[this.ee+
1],10);if(ea>=this.af.length)return ea=new fa,ea.ih(this.af,-1,this.Ba,this.pb,0),ea;var ca=new fa;ca.ih(this.af,ea,this.Ba,this.pb,this.Pc+1);return ca};fa.prototype.getBBox=function(ea){if(this.gm())ea.x1=this.af[this.ee+2+0],ea.y1=this.af[this.ee+2+1],ea.x2=this.af[this.ee+2+2],ea.y2=this.af[this.ee+2+3];else{for(var ca=1.79769E308,x=oa.a.MIN,y=1.79769E308,h=oa.a.MIN,e=0;4>e;++e){var b=this.af[this.ee+2+2*e],a=this.af[this.ee+2+2*e+1];ca=Math.min(ca,b);x=Math.max(x,b);y=Math.min(y,a);h=Math.max(h,
a)}ea.x1=ca;ea.y1=y;ea.x2=x;ea.y2=h}};fa.prototype.OC=function(){if(this.de.length)return this.de[0];var ea=new ka.a,ca=new ka.a,x=new la.a;x.ld();var y=this.ah(),h=new la.a;h.ld();for(var e=this.ah();!e.Gc(x);e=e.eh())h=e;x=Array(8);e=Array(8);y.Ie(0,x);ea.x=(x[0]+x[2]+x[4]+x[6])/4;ea.y=(x[1]+x[3]+x[5]+x[7])/4;h.Ie(h.gk()-1,e);ca.x=(e[0]+e[2]+e[4]+e[6])/4;ca.y=(e[1]+e[3]+e[5]+e[7])/4;.01>Math.abs(ea.x-ca.x)&&.01>Math.abs(ea.y-ca.y)&&this.de.push(0);ea=Math.atan2(ca.y-ea.y,ca.x-ea.x);ea*=180/3.1415926;
0>ea&&(ea+=360);this.de.push(ea);return 0};return fa}();va.a=Ba},490:function(Ba,va,r){var oa=r(477),ka=r(99),la=r(88);Ba=function(){function fa(){this.hl=this.Jd=0;this.pb=this.Ba=this.jc=null;this.Pc=0}fa.prototype.ld=function(){this.hl=this.Jd=-1;this.Pc=0};fa.prototype.ih=function(ea,ca,x,y,h,e){this.Jd=ca;this.hl=x;this.jc=ea;this.Ba=y;this.pb=h;this.Pc=e};fa.prototype.Gc=function(ea){return this.Jd===ea.Jd};fa.prototype.gk=function(){return parseInt(this.jc[this.Jd],10)};fa.prototype.Si=function(){return parseInt(this.jc[this.Jd+
2],10)};fa.prototype.gh=function(){return parseInt(this.jc[this.Jd+1],10)};fa.prototype.gm=function(){return 0<this.jc[this.hl]};fa.prototype.uda=function(){return Math.abs(this.jc[this.hl])};fa.prototype.eh=function(){var ea=this.gm(),ca=ea?5:11;if(this.Jd>=this.hl+(ea?6:10)+(this.uda()-1)*ca)return ca=new fa,ca.ih(this.jc,-1,-1,this.Ba,this.pb,0),ca;ea=new fa;ea.ih(this.jc,this.Jd+ca,this.hl,this.Ba,this.pb,this.Pc+1);return ea};fa.prototype.Jca=function(ea){var ca=this.gk();return 0>ea||ea>=ca?
-1:parseInt(this.jc[this.Jd+1],10)+ea};fa.prototype.Ie=function(ea,ca){ea=this.Jca(ea);if(!(0>ea)){var x=new oa.a;x.ih(this.jc,this.hl,this.Ba,this.pb,0);if(x.gm()){var y=new ka.a;x.getBBox(y);x=y.y1<y.y2?y.y1:y.y2;y=y.y1>y.y2?y.y1:y.y2;ea*=8;ca[0]=this.pb[ea];ca[1]=x;ca[2]=this.pb[ea+2];ca[3]=ca[1];ca[4]=this.pb[ea+4];ca[5]=y;ca[6]=this.pb[ea+6];ca[7]=ca[5]}else for(ea*=8,x=0;8>x;++x)ca[x]=this.pb[ea+x]}};fa.prototype.ke=function(ea){var ca=new oa.a;ca.ih(this.jc,this.hl,this.Ba,this.pb,0);if(ca.gm()){var x=
this.jc[this.Jd+3],y=this.jc[this.Jd+4];if(x>y){var h=x;x=y;y=h}h=new ka.a;ca.getBBox(h);ca=h.y1<h.y2?h.y1:h.y2;h=h.y1>h.y2?h.y1:h.y2;ea[0]=x;ea[1]=ca;ea[2]=y;ea[3]=ca;ea[4]=y;ea[5]=h;ea[6]=x;ea[7]=h}else for(x=this.Jd+3,y=0;8>y;++y)ea[y]=this.jc[x+y]};fa.prototype.getBBox=function(ea){var ca=new oa.a;ca.ih(this.jc,this.hl,this.Ba,this.pb,0);if(ca.gm()){var x=this.jc[this.Jd+3],y=this.jc[this.Jd+4];if(x>y){var h=x;x=y;y=h}h=new ka.a;ca.getBBox(h);ca=h.y1<h.y2?h.y1:h.y2;h=h.y1>h.y2?h.y1:h.y2;ea[0]=
x;ea[1]=ca;ea[2]=y;ea[3]=h}else{x=1.79769E308;y=la.a.MIN;ca=1.79769E308;h=la.a.MIN;for(var e=this.Jd+3,b=0;4>b;++b){var a=this.jc[e+2*b],f=this.jc[e+2*b+1];x=Math.min(x,a);y=Math.max(y,a);ca=Math.min(ca,f);h=Math.max(h,f)}ea[0]=x;ea[1]=ca;ea[2]=y;ea[3]=h}};return fa}();va.a=Ba}}]);}).call(this || window)
