/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[11],{581:function(ya,ta,n){n.r(ta);var pa=n(0),na=n(1);n.n(na);var oa=n(3),ka=n(195);ya=n(61);var ja=n(120),fa=n(328),x=n(100),y=n(327);n=n(495);var r=window,h=function(){function e(a,w,z){var aa=-1===a.indexOf("?")?"?":"&";switch(w){case x.a.NEVER_CACHE:this.url="".concat(a+aa,"_=").concat(Object(na.uniqueId)());break;default:this.url=a}this.Nf=z;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);this.request.setRequestHeader("X-Requested-With",
"XMLHttpRequest");this.request.overrideMimeType?this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=y.a.NOT_STARTED}e.prototype.start=function(a,w){var z=this,aa=this,ca=this.request,ba;aa.cE=0;a&&Object.keys(a).forEach(function(ha){z.request.setRequestHeader(ha,a[ha])});w&&(this.request.withCredentials=w);this.JM=setInterval(function(){var ha=0===window.document.URL.indexOf("file:///");ha=200===ca.status||
ha&&0===ca.status;if(ca.readyState!==y.b.DONE||ha){try{ca.responseText}catch(ea){return}aa.cE<ca.responseText.length&&(ba=aa.ZDa())&&aa.trigger(e.Events.DATA,[ba]);0===ca.readyState&&(clearInterval(aa.JM),aa.trigger(e.Events.DONE))}else clearInterval(aa.JM),aa.trigger(e.Events.DONE,["Error received return status ".concat(ca.status)])},1E3);this.request.send(null);this.status=y.a.STARTED};e.prototype.ZDa=function(){var a=this.request,w=a.responseText;if(0!==w.length)if(this.cE===w.length)clearInterval(this.JM),
this.trigger(e.Events.DONE);else return w=Math.min(this.cE+3E6,w.length),a=r.s7(a,this.cE,!0,w),this.cE=w,a};e.prototype.abort=function(){clearInterval(this.JM);var a=this;this.request.onreadystatechange=function(){Object(oa.i)("StreamingRequest aborted");a.status=y.a.ABORTED;return a.trigger(e.Events.ABORTED)};this.request.abort()};e.prototype.finish=function(){var a=this;this.request.onreadystatechange=function(){a.status=y.a.SUCCESS;return a.trigger(e.Events.DONE)};this.request.abort()};e.Events=
{DONE:"done",DATA:"data",ABORTED:"aborted"};return e}();Object(ya.a)(h);var f;(function(e){e[e.LOCAL_HEADER=0]="LOCAL_HEADER";e[e.FILE=1]="FILE";e[e.CENTRAL_DIR=2]="CENTRAL_DIR"})(f||(f={}));var b=function(e){function a(){var w=e.call(this)||this;w.buffer="";w.state=f.LOCAL_HEADER;w.EY=4;w.$p=null;w.az=ka.c;w.Rr={};return w}Object(pa.c)(a,e);a.prototype.PDa=function(w){var z;for(w=this.buffer+w;w.length>=this.az;)switch(this.state){case f.LOCAL_HEADER:this.$p=z=this.cEa(w.slice(0,this.az));if(z.Qz!==
ka.g)throw Error("Wrong signature in local header: ".concat(z.Qz));w=w.slice(this.az);this.state=f.FILE;this.az=z.VQ+z.ov+z.CC+this.EY;this.trigger(a.Events.HEADER,[z]);break;case f.FILE:this.$p.name=w.slice(0,this.$p.ov);this.Rr[this.$p.name]=this.$p;z=this.az-this.EY;var aa=w.slice(this.$p.ov+this.$p.CC,z);this.trigger(a.Events.FILE,[this.$p.name,aa,this.$p.qR]);w=w.slice(z);if(w.slice(0,this.EY)===ka.h)this.state=f.LOCAL_HEADER,this.az=ka.c;else return this.state=f.CENTRAL_DIR,!0}this.buffer=w;
return!1};a.Events={HEADER:"header",FILE:"file"};return a}(fa.a);Object(ya.a)(b);ya=function(e){function a(w,z,aa,ca,ba){aa=e.call(this,w,aa,ca)||this;aa.url=w;aa.stream=new h(w,z);aa.Pe=new b;aa.Oaa=window.createPromiseCapability();aa.xba={};aa.Nf=ba;return aa}Object(pa.c)(a,e);a.prototype.iF=function(w){var z=this;this.request([this.Cm,this.Do,this.Bm]);this.stream.addEventListener(h.Events.DATA,function(aa){try{if(z.Pe.PDa(aa))return z.stream.finish()}catch(ca){throw z.stream.abort(),z.Au(ca),
w(ca),ca;}});this.stream.addEventListener(h.Events.DONE,function(aa){z.mDa=!0;z.Oaa.resolve();aa&&(z.Au(aa),w(aa))});this.Pe.addEventListener(b.Events.HEADER,Object(na.bind)(this.wba,this));this.Pe.addEventListener(b.Events.FILE,Object(na.bind)(this.tEa,this));return this.stream.start(this.Nf,this.withCredentials)};a.prototype.l7=function(w){var z=this;this.Oaa.promise.then(function(){w(Object.keys(z.Pe.Rr))})};a.prototype.Ns=function(){return!0};a.prototype.request=function(w){var z=this;this.mDa&&
w.forEach(function(aa){z.xba[aa]||z.KKa(aa)})};a.prototype.wba=function(){};a.prototype.abort=function(){this.stream&&this.stream.abort()};a.prototype.KKa=function(w){this.trigger(ja.a.Events.PART_READY,[{Lb:w,error:"Requested part not found",xl:!1,ri:!1}])};a.prototype.tEa=function(w,z,aa){this.xba[w]=!0;this.trigger(ja.a.Events.PART_READY,[{Lb:w,data:z,xl:!1,ri:!1,error:null,te:aa}])};return a}(ja.a);Object(n.a)(ya);Object(n.b)(ya);ta["default"]=ya}}]);}).call(this || window)
