/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[14],{441:function(Ba,ua,r){r.r(ua);var pa=r(1),ka=r(0);r.n(ka);var ma=r(2),fa=r(149);Ba=r(49);var da=r(94),z=r(246),x=r(71),y=r(245);r=r(374);var f=window,e=function(){function h(n,aa,w){var ea=-1===n.indexOf("?")?"?":"&";switch(aa){case x.a.NEVER_CACHE:this.url=n+ea+"_="+Object(ka.uniqueId)();break;default:this.url=n}this.df=w;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);this.request.setRequestHeader("X-Requested-With",
"XMLHttpRequest");this.request.overrideMimeType?this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=y.a.NOT_STARTED}h.prototype.start=function(n,aa){var w=this,ea=this,ja=this.request,ba;ea.lx=0;n&&Object.keys(n).forEach(function(ca){w.request.setRequestHeader(ca,n[ca])});aa&&(this.request.withCredentials=aa);this.fE=setInterval(function(){var ca=0===window.document.URL.indexOf("file:///");ca=200===ja.status||
ca&&0===ja.status;if(ja.readyState!==y.b.DONE||ca){try{ja.responseText}catch(ia){return}ea.lx<ja.responseText.length&&(ba=ea.sha())&&ea.trigger(h.Events.DATA,[ba]);0===ja.readyState&&(clearInterval(ea.fE),ea.trigger(h.Events.DONE))}else clearInterval(ea.fE),ea.trigger(h.Events.DONE,["Error received return status "+ja.status])},1E3);this.request.send(null);this.status=y.a.STARTED};h.prototype.sha=function(){var n=this.request,aa=n.responseText;if(0!==aa.length)if(this.lx===aa.length)clearInterval(this.fE),
this.trigger(h.Events.DONE);else return aa=Math.min(this.lx+3E6,aa.length),n=f.bU(n,this.lx,!0,aa),this.lx=aa,n};h.prototype.abort=function(){clearInterval(this.fE);var n=this;this.request.onreadystatechange=function(){Object(ma.j)("StreamingRequest aborted");n.status=y.a.ABORTED;return n.trigger(h.Events.ABORTED)};this.request.abort()};h.prototype.finish=function(){var n=this;this.request.onreadystatechange=function(){n.status=y.a.SUCCESS;return n.trigger(h.Events.DONE)};this.request.abort()};h.Events=
{DONE:"done",DATA:"data",ABORTED:"aborted"};return h}();Object(Ba.a)(e);var b;(function(h){h[h.LOCAL_HEADER=0]="LOCAL_HEADER";h[h.FILE=1]="FILE";h[h.CENTRAL_DIR=2]="CENTRAL_DIR"})(b||(b={}));var a=function(h){function n(){var aa=h.call(this)||this;aa.buffer="";aa.state=b.LOCAL_HEADER;aa.VM=4;aa.Xl=null;aa.vt=fa.c;aa.Hn={};return aa}Object(pa.c)(n,h);n.prototype.lha=function(aa){var w;for(aa=this.buffer+aa;aa.length>=this.vt;)switch(this.state){case b.LOCAL_HEADER:this.Xl=w=this.wha(aa.slice(0,this.vt));
if(w.bu!==fa.g)throw Error("Wrong signature in local header: "+w.bu);aa=aa.slice(this.vt);this.state=b.FILE;this.vt=w.wH+w.wq+w.gw+this.VM;this.trigger(n.Events.HEADER,[w]);break;case b.FILE:this.Xl.name=aa.slice(0,this.Xl.wq);this.Hn[this.Xl.name]=this.Xl;w=this.vt-this.VM;var ea=aa.slice(this.Xl.wq+this.Xl.gw,w);this.trigger(n.Events.FILE,[this.Xl.name,ea,this.Xl.OH]);aa=aa.slice(w);if(aa.slice(0,this.VM)===fa.h)this.state=b.LOCAL_HEADER,this.vt=fa.c;else return this.state=b.CENTRAL_DIR,!0}this.buffer=
aa;return!1};n.Events={HEADER:"header",FILE:"file"};return n}(z.a);Object(Ba.a)(a);Ba=function(h){function n(aa,w,ea,ja,ba){ea=h.call(this,aa,ea,ja)||this;ea.url=aa;ea.stream=new e(aa,w);ea.Zd=new a;ea.cX=window.createPromiseCapability();ea.EX={};ea.df=ba;return ea}Object(pa.c)(n,h);n.prototype.ay=function(aa){var w=this;this.request([this.vj,this.Kk,this.uj]);this.stream.addEventListener(e.Events.DATA,function(ea){try{if(w.Zd.lha(ea))return w.stream.finish()}catch(ja){throw w.stream.abort(),w.cw(ja),
aa(ja),ja;}});this.stream.addEventListener(e.Events.DONE,function(ea){w.Qga=!0;w.cX.resolve();ea&&(w.cw(ea),aa(ea))});this.Zd.addEventListener(a.Events.HEADER,Object(ka.bind)(this.DX,this));this.Zd.addEventListener(a.Events.FILE,Object(ka.bind)(this.Mha,this));return this.stream.start(this.df,this.withCredentials)};n.prototype.ZT=function(aa){var w=this;this.cX.promise.then(function(){aa(Object.keys(w.Zd.Hn))})};n.prototype.qo=function(){return!0};n.prototype.request=function(aa){var w=this;this.Qga&&
aa.forEach(function(ea){w.EX[ea]||w.qma(ea)})};n.prototype.DX=function(){};n.prototype.abort=function(){this.stream&&this.stream.abort()};n.prototype.qma=function(aa){this.trigger(da.a.Events.PART_READY,[{Za:aa,error:"Requested part not found",Fi:!1,Wf:!1}])};n.prototype.Mha=function(aa,w,ea){this.EX[aa]=!0;this.trigger(da.a.Events.PART_READY,[{Za:aa,data:w,Fi:!1,Wf:!1,error:null,ad:ea}])};return n}(da.a);Object(r.a)(Ba);Object(r.b)(Ba);ua["default"]=Ba}}]);}).call(this || window)
