/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[14],{461:function(Ba,va,r){function oa(){return!1}function ka(z,w,da){if(!(w in n))return!0;w=n[w];for(var ja=0;ja<w.length;ja++){var aa=z;var ba=w[ja];var ia=da;if(ba.name in aa){var ha="",ma=!1;aa=aa[ba.name];switch(ba.type){case "s":ha="String";ma=Object(fa.isString)(aa);break;case "a":ha="Array";ma=Object(fa.isArray)(aa);break;case "n":ha="Number";ma=Object(fa.isNumber)(aa)&&Object(fa.isFinite)(aa);break;case "o":ha="Object",
ma=Object(fa.isObject)(aa)&&!Object(fa.isArray)(aa)}ma||ia.reject('Expected response field "'+ba.name+'" to have type '+ha);ba=ma}else ia.reject('Response missing field "'+ba.name+'"'),ba=!1;if(!ba)return!1}return!0}r.r(va);var la=r(0),fa=r(1);r.n(fa);var ea=r(2);Ba=r(48);var ca=r(34),x=r(478),y=r(98),h=r(386),e=r(42),b=r(172),a=function(){function z(){this.request=this.result=null;this.state=0;var w=this;w.promise=new Promise(function(da,ja){w.resolve=function(){if(0===w.state||4===w.state)w.state=
1,w.result=arguments[0],da.apply(null,arguments)};w.reject=function(){if(0===w.state||4===w.state)w.state=2,ja.apply(null,arguments)}})}z.prototype.Bt=function(){return 1===(this.state&1)};z.prototype.Jfa=function(){return 2===(this.state&2)};z.prototype.$i=function(){return!this.Jfa()&&!this.Bt()};z.prototype.kfa=function(){return 4===(this.state&4)};z.prototype.WM=function(){this.state|=4};return z}(),f=function(){function z(){this.it={};this.Jb=[]}z.prototype.pop=function(){var w=this.Jb.pop();
this.it[w.key]=void 0;return w};z.prototype.push=function(w,da){da={key:w,data:da};this.Jb.push(da);this.it[w]=da.data};z.prototype.contains=function(w){return!!this.it[w]};z.prototype.get=function(w){return this.it[w]};z.prototype.set=function(w,da){var ja=this;this.it[w]=da;this.Jb.forEach(function(aa,ba){aa.key===w&&(ja.Jb[ba]=aa)})};z.prototype.remove=function(w){var da=this;this.it[w]=void 0;this.Jb.forEach(function(ja,aa){ja.key===w&&da.Jb.splice(aa,1)})};z.prototype.length=function(){return this.Jb.length};
return z}(),n={pages:[{name:"pages",type:"a"}],pdf:[{name:"url",type:"s"}],docmod:[{name:"url",type:"s"},{name:"rID",type:"s"}],health:[],tiles:[{name:"z",type:"n"},{name:"rID",type:"n"},{name:"tiles",type:"a"},{name:"size",type:"n"}],cAnnots:[{name:"annots",type:"a"}],annots:[{name:"url",type:"s"},{name:"name",type:"s"}],image:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],text:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],ApString2Xod:[{name:"url",type:"s"},
{name:"rID",type:"s"}]};r=function(){function z(w,da,ja){var aa=this;this.xN=this.$S=!1;this.ph=this.QF=this.Ku=this.vL=this.ZH=this.Om=null;this.sm=new a;this.Hp=new a;this.PB=!1;this.Bf=this.De=this.Ee=this.sf=null;this.Vf=[];this.AC=[];this.cache={};this.timeStamp=0;this.kh=[];this.jj=[];this.cJ=null;this.NS=!1;this.AZ=this.id=null;this.gL=this.xV=oa;this.hi=0;this.kK=!1;this.dX=1;this.fj={};this.Zr=0;this.au=new f;da.endsWith("/")||(da+="/");ja=ja||{};this.$S=ja.disableWebsockets||!1;this.xN=
ja.singleServerMode||!1;null!=ja.customQueryParameters&&Object(e.b)("wvsQueryParameters",ja.customQueryParameters);da.endsWith("blackbox/")||(da+="blackbox/");this.Om=ja.uploadData||null;this.Ku=ja.uriData||null;this.ZH=ja.cacheKey||null;this.vL=ja.officeOptions||null;this.Ue=da;this.DI=w;this.Eo(!0);this.us=(new x.a(da,null,this.Uh())).uba(!this.$S,function(ba){aa.bha(ba)},function(){return null},function(){aa.PB=!1},function(){aa.gka()})}z.prototype.d9=function(){var w=this;return new Promise(function(da,
ja){var aa=new XMLHttpRequest;aa.open("GET",w.Ue+"ck");aa.withCredentials=w.Uh();aa.onreadystatechange=function(){aa.readyState===XMLHttpRequest.DONE&&(200===aa.status?da():ja())};aa.send()})};z.prototype.Rla=function(w){this.xV=w||oa;this.gL=oa};z.prototype.J7=function(){this.dZ();return this.us.Sp(!0)};z.prototype.dZ=function(){Object(la.b)(this,void 0,void 0,function(){return Object(la.d)(this,function(w){switch(w.label){case 0:return this.Hp=new a,this.sm=new a,this.PB=!1,this.id=null,this.NS=
!1,[4,this.d9()];case 1:return w.da(),[2]}})})};z.prototype.gka=function(){this.xV();this.dZ();this.sf&&(this.sf.$i()?this.wh(this.sf.request):this.sf.Bt()&&this.gL(this.sf.result.url,"pdf")&&(this.sf=null,this.cZ()));this.Bf&&this.Bf.$i()&&this.wh(this.Bf.request);this.Ee&&this.Ee.$i()?this.wh(this.Ee.request):this.De&&this.De.$i()&&this.kV();var w;for(w=0;w<this.kh.length;w++)this.kh[w]&&(this.kh[w].$i()?this.wh(this.kh[w].request):this.kh[w].Bt()&&this.gL(this.kh[w].result.url,"image")&&(this.kh[w]=
null,this.OE(Object(fa.uniqueId)(),w)));for(w=0;w<this.jj.length;w++)this.jj[w]&&this.jj[w].$i()&&!this.jj[w].kfa()&&this.wh(this.jj[w].request);for(w=0;w<this.Vf.length;w++)this.Vf[w]&&this.Vf[w].$i()&&this.wh(this.Vf[w].request)};z.prototype.Uea=function(){return this.PB?Promise.resolve():(this.PB=!0,this.timeStamp=Date.now(),this.us.xD())};z.prototype.moa=function(){var w=this,da,ja,aa,ba,ia;return new Promise(function(ha,ma){if(w.Om)da=new FormData,da.append("file",w.Om.fileHandle,w.Om.fileHandle.name),
ja=w.Om.loadCallback,ba="upload",aa=w.Om.extension;else if(w.Ku)da={uri:w.Ku.uri,bsa:w.Ku.shareId},da=Object.keys(da).map(function(qa){return qa+"="+(da[qa]?encodeURIComponent(da[qa]):"")}).join("&"),ia="application/x-www-form-urlencoded; charset=UTF-8",ja=w.Ku.loadCallback,ba="url",aa=w.Ku.extension;else{ha();return}var na=new XMLHttpRequest,sa=Object(ca.j)(w.Ue,"AuxUpload");sa=Object(b.a)(sa,{type:ba,ext:aa});na.open("POST",sa);na.withCredentials=w.Uh();ia&&na.setRequestHeader("Content-Type",ia);
na.addEventListener("load",function(){if(na.readyState===na.DONE&&200===na.status){var qa=JSON.parse(na.response);w.DI=qa.uri;ja(qa);ha(qa)}});na.addEventListener("error",function(){ma(na.statusText+" "+JSON.stringify(na))});w.Om&&null!=w.Om.onProgress&&(na.upload.onprogress=function(qa){w.Om.onProgress(qa)});na.send(da)})};z.prototype.Yja=function(w){this.password=w||null;this.sm.Bt()||(this.sm=new a,this.wh({t:"pages"}));return this.sm.promise};z.prototype.By=function(w){this.cJ=w||null;this.sm.Bt()||
this.wh({t:"pages"});return this.sm.promise};z.prototype.ew=function(w){w=Object.assign(w,{uri:encodeURIComponent(this.DI)});this.cJ&&(w.ext=this.cJ);this.ph&&(w.c=this.ph);this.password&&(w.pswd=this.password);this.ZH&&(w.cacheKey=this.ZH);this.vL&&(w.officeOptions=this.vL);return w};z.prototype.Gka=function(){0<this.au.length()&&10>=this.Zr&&this.Hka(this.au.pop().data)};z.prototype.j7=function(w){0<this.au.length()&&this.au.contains(w)&&this.au.remove(w)};z.prototype.wh=function(w){w=this.ew(w);
this.us.send(w)};z.prototype.vZ=function(w,da){10<this.Zr?this.au.push(w,da):(this.Zr++,w=this.ew(da),this.us.send(w))};z.prototype.Hka=function(w){this.Zr++;w=this.ew(w);this.us.send(w)};z.prototype.yl=function(w){return w};z.prototype.wV=function(w){this.xN&&w?Object(ea.j)("Server failed health check. Single server mode ignoring check."):!this.Cqa&&w&&3>=this.hi?(this.kK=!0,this.us.Sp()):3<this.hi&&(this.xN=!0)};z.prototype.bha=function(w){var da=this,ja=w.data,aa=w.err,ba=w.t;switch(ba){case "upload":aa?
this.noa.reject(aa):this.noa.resolve("Success");break;case "pages":aa?this.sm.reject(aa):ka(ja,ba,this.sm)&&this.sm.resolve(ja);break;case "config":if(aa)this.Hp.reject(aa);else if(ka(ja,ba,this.Hp)){this.wV(ja.unhealthy);ja.id&&(this.id=ja.id);if(ja.auth){var ia=Object(e.a)("wvsQueryParameters");ia.auth=ja.auth;Object(e.b)("wvsQueryParameters",ia)}ja.serverVersion&&(this.QF=ja.serverVersion,Object(ea.h)("[WebViewer Server] server version: "+this.QF));ja.serverID?(this.hi=ja.serverID===this.AZ&&this.kK?
this.hi+1:0,this.AZ=ja.serverID):this.hi=0;this.kK=!1;this.Hp.resolve(ja)}break;case "health":aa?this.Hp.reject(aa):ka(ja,ba,this.Hp)&&this.wV(ja.unhealthy);break;case "pdf":ja.url=Object(b.a)(this.Ue+"../"+encodeURI(ja.url));aa?this.sf.reject(aa):ka(ja,ba,this.sf)&&this.sf.resolve(ja);break;case "ApString2Xod":ja.url=Object(b.a)(this.Ue+"../data/"+encodeURI(ja.url));aa?this.fj[ja.rID].reject(aa):ka(ja,ba,this.fj[ja.rID])&&this.fj[ja.rID].resolve(ja);break;case "docmod":ja.url=Object(b.a)(this.Ue+
"../"+encodeURI(ja.url));aa?this.fj[ja.rID].reject(aa):ka(ja,ba,this.sf)&&this.fj[ja.rID].resolve(ja);break;case "xod":if(aa)this.Ee&&this.Ee.$i()&&this.Ee.reject(aa),this.De&&this.De.$i()&&this.De.reject(aa);else if(ja.notFound)ja.noCreate||this.Ee&&this.Ee.$i()&&this.Ee.resolve(ja),this.De&&this.De.$i()&&this.De.resolve(ja);else{ja.url&&(ja.url=Object(b.a)(this.Ue+"../"+encodeURI(ja.url)));if(!this.De||this.De.Bt())this.De=new a,this.De.request={t:"xod",noCreate:!0};this.Ee||(this.Ee=new a,this.Ee.request=
{t:"xod"});this.De.resolve(ja);this.Ee.resolve(ja)}break;case "cAnnots":ia=this.Bf;if(aa)ia.reject(aa);else if(ka(ja,ba,ia)){ia.WM();var ha=[],ma=ja.annots;ja=function(pa){var wa=ma[pa].s,Aa=ma[pa].e,Ha=na.Ue+"../"+encodeURI(ma[pa].xfdf),Ia="true"===ma[pa].hasAppearance?Object(b.a)(Ha+".xodapp"):null,Da=Object(fa.range)(wa,Aa+1);ha[pa]={range:Da,promise:new Promise(function(Ja,Va){var Na=new XMLHttpRequest;Na.open("GET",Object(b.a)(Ha));Na.responseType="text";Na.withCredentials=da.Uh();Na.addEventListener("load",
function(){Na.readyState===Na.DONE&&200===Na.status&&Ja({qr:Na.response,ol:Ia,range:Da})});Na.addEventListener("error",function(){Va(Na.statusText+" "+JSON.stringify(Na))});Na.send()})}};var na=this;for(aa=0;aa<ma.length;aa++)ja(aa);ia.resolve(ha)}break;case "annots":if(aa)this.Bf.reject(aa);else if(ka(ja,ba,this.Bf)){this.Bf.WM();var sa=new XMLHttpRequest;ia=this.Ue+"../"+encodeURI(ja.url);var qa=ja.hasAppearance?Object(b.a)(ia+".xodapp"):null;sa.open("GET",Object(b.a)(ia));sa.responseType="text";
sa.withCredentials=this.Uh();sa.addEventListener("load",function(){sa.readyState===sa.DONE&&200===sa.status&&da.Bf.resolve({qr:sa.response,ol:qa})});sa.addEventListener("error",function(){da.Bf.reject(sa.statusText+" "+JSON.stringify(sa))});sa.send()}break;case "image":this.Zr--;var ra=this.kh[ja.p];aa?ra.promise.reject(aa):ka(ja,ba,ra)&&(ra.result=ja,ra.result.url=Object(b.a)(this.Ue+"../"+encodeURI(ra.result.url)),ra.resolve(ra.result));break;case "tiles":this.Zr--;ra=ja.rID;ia=this.Vf[ra];this.Vf[ra]=
null;this.AC.push(ra);if(aa)ia.reject(aa);else if(ka(ja,ba,ia)){for(aa=0;aa<ja.tiles.length;aa++)ja.tiles[aa]=Object(b.a)(this.Ue+"../"+encodeURI(ja.tiles[aa]));ia.resolve(ja)}break;case "text":ra=this.jj[ja.p];if(aa)ra.reject(aa);else if(ka(ja,ba,ra)){ra.WM();var ua=new XMLHttpRequest;ja=Object(b.a)(this.Ue+"../"+encodeURI(ja.url));ua.open("GET",ja);ua.withCredentials=this.Uh();ua.addEventListener("load",function(){ua.readyState===ua.DONE&&200===ua.status&&(ra.result=JSON.parse(ua.response),ra.resolve(ra.result))});
ua.addEventListener("error",function(pa){ra.reject(ua.statusText+" "+JSON.stringify(pa))});ua.send()}break;case "progress":"loading"===ja.t&&this.trigger(y.a.Events.DOCUMENT_LOADING_PROGRESS,[ja.bytes,ja.total])}this.Gka();!ba&&w.echo&&w&&"apstring2xod"===w.echo.t&&(w=w.echo.reqID)&&(2<=parseInt(this.QF,10)?this.fj[w].reject("Message unhandled by server"):this.fj[w].reject())};z.prototype.bca=function(){return Object(la.b)(this,void 0,void 0,function(){return Object(la.d)(this,function(w){switch(w.label){case 0:return[4,
this.Uea()];case 1:return w.da(),[2,this.Hp.promise]}})})};z.prototype.Jba=function(w){for(var da=this,ja=new XMLHttpRequest,aa=Object(b.a)(this.Ue+"aul",{id:this.id}),ba=new FormData,ia={},ha=0;ha<w.body.length;ha++){var ma=w.body[ha];ia[ma.id]=ma.MH.w+";"+ma.MH.h;ba.append(ma.id,ma.MH.dataString)}w={t:"apstring2xod",reqID:this.dX++,parts:ia};var na=this.ew(w);ba.append("msg",JSON.stringify(na));this.fj[na.reqID]=new a;ja.open("POST",aa);ja.withCredentials=this.Uh;aa=new Promise(function(sa,qa){ja.onreadystatechange=
function(){4===ja.readyState&&(200===ja.status?sa():qa("An error occurred while sending down appearance strings to the server"))}});ja.send(ba);return aa.then(function(){return da.fj[na.reqID].promise})};z.prototype.L7=function(){var w=this.QF.split("-")[0].split("."),da=["1","5","9"];if(3!==w.length)throw Error("Invalid WVS version length.");if(3!==da.length)throw Error("Invalid version length.");for(var ja=0;ja<w.length;++ja){if(da.length===ja||w[ja]>da[ja])return-1;if(w[ja]!==da[ja])return 1}return 0};
z.prototype.Dp=function(){return 0>=this.L7()};z.prototype.lJ=function(){this.Bf||(this.Bf=new a,this.Dp()?this.Bf.request={t:"cAnnots"}:this.Bf.request={t:"annots"},this.wh(this.Bf.request));return this.Bf.promise};z.prototype.OE=function(w,da){this.kh[da]||(this.kh[da]=new a,this.kh[da].request={t:"image",p:da},this.vZ(w,this.kh[da].request));return this.kh[da].promise};z.prototype.Zja=function(w){this.jj[w]||(this.jj[w]=new a,this.jj[w].request={t:"text",p:w},this.wh(this.jj[w].request));return this.jj[w].promise};
z.prototype.$ja=function(w,da,ja,aa,ba){var ia=this.Vf.length;this.AC.length&&(ia=this.AC.pop());this.Vf[ia]=new a;this.Vf[ia].request={t:"tiles",p:da,z:ja,r:aa,size:ba,rID:ia};this.vZ(w,this.Vf[ia].request);return this.Vf[ia].promise};z.prototype.cZ=function(){this.sf||(this.sf=new a,this.sf.request={t:"pdf"},this.NS?this.sf.resolve({url:this.DI}):this.wh(this.sf.request));return this.sf.promise};z.prototype.FU=function(w){var da=this,ja=new XMLHttpRequest,aa=Object(b.a)(this.Ue+"aul",{id:this.id}),
ba=new FormData,ia={};w.annots&&(ia.annots="xfdf");w.watermark&&(ia.watermark="png");w.redactions&&(ia.redactions="redact");ia={t:"docmod",reqID:this.dX++,parts:ia};w.print&&(ia.print=!0);var ha=this.ew(ia);ba.append("msg",JSON.stringify(ha));return Promise.all([w.annots,w.watermark,w.redactions].map(function(ma){return Promise.resolve(ma)})).then(function(ma){var na=ma[0],sa=ma[1];ma=ma[2];na&&ba.append("annots",na);sa&&ba.append("watermark",sa);ma&&ba.append("redactions",ma);da.fj[ha.reqID]=new a;
ja.open("POST",aa);ja.withCredentials=da.Uh;na=new Promise(function(qa,ra){ja.onreadystatechange=function(){4===ja.readyState&&(200===ja.status?qa():ra("An error occurred while sending down annotation data to the server"))}});ja.send(ba);return na.then(function(){return da.fj[ha.reqID].promise})})};z.prototype.kV=function(){this.De||(this.De=new a,this.De.request={t:"xod",noCreate:!0},this.wh(this.De.request));return this.De.promise};z.prototype.aka=function(){this.Ee||(this.Ee=new a,this.Ee.request=
{t:"xod"},this.wh(this.Ee.request));return this.Ee.promise};z.prototype.zo=function(){return!0};z.prototype.request=function(){};z.prototype.wY=function(){};z.prototype.abort=function(){for(var w=0;w<this.Vf.length;w++)this.Vf[w]&&(this.Vf[w].resolve(null),this.Vf[w]=null,this.AC.push(w));this.close()};z.prototype.bF=function(w){this.ph=this.ph||{};this.ph.headers=w};z.prototype.Eo=function(w){this.ph=this.ph||{};this.ph.internal=this.ph.internal||{};this.ph.internal.withCredentials=w};z.prototype.Uh=
function(){return this.ph&&this.ph.internal?this.ph.internal.withCredentials:null};z.prototype.getFileData=function(){return Promise.reject()};return z}();Object(Ba.a)(r);Object(h.a)(r);Object(h.b)(r);va["default"]=r},478:function(Ba,va,r){var oa=r(0),ka=r(2),la=r(34),fa=r(42),ea=r(172),ca=r(74),x=function(){function h(e,b,a,f,n,z){void 0===a&&(a=null);void 0===f&&(f=null);void 0===n&&(n=null);void 0===z&&(z=null);this.LW=!1;this.hi=0;this.QR=this.Ioa(e);this.url=b?this.QR+"/"+b:this.QR+"/ws";this.wI=
a;this.Yx=f;this.cw=n;this.yM=z}h.prototype.Ioa=function(e){var b=e.indexOf("://"),a="ws://";0>b?b=0:(5===b&&(a="wss://"),b+=3);var f=e.lastIndexOf("/");0>f&&(f=e.length);return a+e.slice(b,f)};h.prototype.send=function(e){this.So.readyState===WebSocket.CLOSED||this.LW||this.So.send(JSON.stringify(e))};h.prototype.xD=function(){return Object(oa.b)(this,void 0,void 0,function(){var e,b=this;return Object(oa.d)(this,function(){e=Object(fa.a)("wvsQueryParameters");e.bcid=Object(la.k)(8);Object(fa.b)("wvsQueryParameters",
e);return[2,new Promise(function(a,f){var n=Object(ea.a)(b.url);b.So=new WebSocket(n);b.So.onopen=function(){b.Yx&&b.Yx();a()};b.So.onerror=function(z){b.LW=!0;f(z)};b.So.onclose=function(z){var w=z.code;return Object(oa.b)(b,void 0,void 0,function(){var da=this;return Object(oa.d)(this,function(ja){switch(ja.label){case 0:return this.cw&&this.cw(),3E3===w?[3,3]:8>this.hi++?[4,new Promise(function(aa){return setTimeout(function(){return Object(oa.b)(da,void 0,void 0,function(){return Object(oa.d)(this,
function(ba){switch(ba.label){case 0:return this.yM(),[4,this.xD()];case 1:return ba.da(),aa(),[2]}})})},3E3)})]:[3,2];case 1:return ja.da(),[3,3];case 2:f(ca.a),ja.label=3;case 3:return[2]}})})};b.So.onmessage=function(z){z&&z.data&&(z=JSON.parse(z.data),z.hb?b.send({hb:!0}):z.end?close():b.wI(z))}})]})})};h.prototype.Sp=function(e){void 0===e&&(e=!1);this.hi=0;e?this.So.close(3E3):this.So.close();return Promise.resolve()};return h}(),y=function(){function h(e,b,a,f,n,z,w){void 0===f&&(f=null);void 0===
n&&(n=null);void 0===z&&(z=null);void 0===w&&(w=null);this.hi=this.NE=this.id=0;this.nx=!1;this.request=null;e=this.yia(e);this.url=b?e+"/"+b+"pf":e+"/pf";this.JF=a;this.wI=f;this.Yx=n;this.cw=z;this.yM=w}h.prototype.yia=function(e){var b=e.lastIndexOf("/");0>b&&(b=e.length);return e.slice(0,b)};h.prototype.M8=function(e){e=e.split("\n");for(e[e.length-1]&&e.pop();0<e.length&&3>e[e.length-1].length;)"]"===e.pop()&&(this.id=0);0<e.length&&3>e[0].length&&e.shift();for(var b=0;b<e.length;++b)e[b].endsWith(",")&&
(e[b]=e[b].substr(0,e[b].length-1));return e};h.prototype.mZ=function(){return Object(oa.b)(this,void 0,void 0,function(){var e=this;return Object(oa.d)(this,function(b){switch(b.label){case 0:return 8>this.hi++?[4,new Promise(function(a){return setTimeout(function(){e.yM();e.xD();a()},3E3)})]:[3,2];case 1:b.da(),b.label=2;case 2:return[2]}})})};h.prototype.Aia=function(e){Object(oa.b)(this,void 0,void 0,function(){var b,a;return Object(oa.d)(this,function(f){switch(f.label){case 0:b=null,a=0,f.label=
1;case 1:if(!(a<e.length))return[3,6];b=JSON.parse(e[a]);if(!b)return[3,5];if(!b.end)return[3,2];close();return[3,5];case 2:if(!b.id||Number(b.id)===this.id)return[3,4];Object(ka.j)("Reconnecting, new server detected");this.Sp();return[4,this.mZ()];case 3:return f.da(),[3,5];case 4:b.hb&&Number(b.id)===this.id?this.send({hb:!0}):this.nx||this.wI(b),f.label=5;case 5:return++a,[3,1];case 6:return[2]}})})};h.prototype.Zga=function(e){Object(oa.b)(this,void 0,void 0,function(){var b,a,f;return Object(oa.d)(this,
function(n){switch(n.label){case 0:if(!(3<=e.readyState))return[3,2];try{b=e.responseText.length}catch(z){return Object(ka.h)("caught exception"),[2]}if(0<b)try{a=this.M8(e.responseText),0===this.id&&0<a.length&&(f=JSON.parse(a.shift()),this.id=f.id,this.hi=0),this.Aia(a)}catch(z){}return this.nx?[3,2]:[4,this.ET()];case 1:n.da(),n.label=2;case 2:return[2]}})})};h.prototype.ET=function(){return Object(oa.b)(this,void 0,void 0,function(){var e=this;return Object(oa.d)(this,function(){return[2,new Promise(function(b,
a){function f(){return Object(oa.b)(e,void 0,void 0,function(){return Object(oa.d)(this,function(z){switch(z.label){case 0:a(),this.Sp(),z.label=1;case 1:return this.nx&&8>this.hi?[4,this.mZ()]:[3,3];case 2:return z.da(),[3,1];case 3:return[2]}})})}e.request=new XMLHttpRequest;e.request.withCredentials=e.JF;var n=Object(ea.a)(e.url,0!==e.id?{id:String(e.id),uc:String(e.NE)}:{uc:String(e.NE)});e.NE++;e.request.open("GET",n,!0);e.request.setRequestHeader("Cache-Control","no-cache");e.request.setRequestHeader("X-Requested-With",
"XMLHttpRequest");e.request.onreadystatechange=function(){e.Zga(e.request)};e.request.addEventListener("error",f);e.request.addEventListener("timeout",f);e.request.addEventListener("load",function(){e.Yx&&e.Yx();b()});e.request.send()})]})})};h.prototype.xD=function(){var e=Object(fa.a)("wvsQueryParameters");e.bcid=Object(la.k)(8);Object(fa.b)("wvsQueryParameters",e);this.NE=this.id=0;this.nx=!1;return this.ET()};h.prototype.send=function(e){var b=this,a=new XMLHttpRequest;a.withCredentials=this.JF;
var f=Object(ea.a)(this.url,{id:String(this.id)}),n=new FormData;n.append("data",JSON.stringify(e));a.addEventListener("error",function(){b.Sp()});a.open("POST",f);a.setRequestHeader("X-Requested-With","XMLHttpRequest");a.send(n)};h.prototype.Sp=function(){this.id=0;this.nx=!0;this.cw&&this.cw();this.request.abort();return Promise.resolve()};return h}();Ba=function(){function h(e,b,a){this.pS=e;this.target=b;this.JF=a}h.prototype.uba=function(e,b,a,f,n){void 0===e&&(e=!0);void 0===b&&(b=null);void 0===
a&&(a=null);void 0===f&&(f=null);void 0===n&&(n=null);return e?new x(this.pS,this.target,b,a,f,n):new y(this.pS,this.target,this.JF,b,a,f,n)};return h}();va.a=Ba}}]);}).call(this || window)
