/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[13],{583:function(ya,ta,n){function pa(){return!1}function na(z,aa,ca){if(!(aa in w))return!0;aa=w[aa];for(var ba=0;ba<aa.length;ba++){var ha=z;var ea=aa[ba];var ma=ca;if(ea.name in ha){var la="",ia=!1;ha=ha[ea.name];switch(ea.type){case "s":la="String";ia=Object(ja.isString)(ha);break;case "a":la="Array";ia=Object(ja.isArray)(ha);break;case "n":la="Number";ia=Object(ja.isNumber)(ha)&&Object(ja.isFinite)(ha);break;case "o":la="Object",
ia=Object(ja.isObject)(ha)&&!Object(ja.isArray)(ha)}ia||ma.reject('Expected response field "'.concat(ea.name,'" to have type ').concat(la));ea=ia}else ma.reject('Response missing field "'.concat(ea.name,'"')),ea=!1;if(!ea)return!1}return!0}function oa(z){for(var aa=0,ca=["locale","excelMaxAllowedCellCount","applyPageBreaksToSheet","excelDefaultCellBorderWidth","displayChangeTracking"];aa<ca.length;aa++){var ba=ca[aa],ha=ba;ba=ba.charAt(0).toUpperCase()+ba.slice(1);z[ha]&&(Object.defineProperty(z,
ba,Object.getOwnPropertyDescriptor(z,ha)),delete z[ha])}return z}n.r(ta);var ka=n(0),ja=n(1);n.n(ja);var fa=n(3);ya=n(61);var x=n(34),y=n(601),r=n(120),h=n(495),f=n(54),b=n(219),e=function(){function z(){this.request=this.result=null;this.state=0;var aa=this;aa.promise=new Promise(function(ca,ba){aa.resolve=function(){if(0===aa.state||4===aa.state)aa.state=1,aa.result=arguments[0],ca.apply(null,arguments)};aa.reject=function(){if(0===aa.state||4===aa.state)aa.state=2,ba.apply(null,arguments)}})}z.prototype.Py=
function(){return 1===(this.state&1)};z.prototype.Sza=function(){return 2===(this.state&2)};z.prototype.Vl=function(){return!this.Sza()&&!this.Py()};z.prototype.kza=function(){return 4===(this.state&4)};z.prototype.$X=function(){this.state|=4};return z}(),a=function(){function z(){this.Cy={};this.Ic=[]}z.prototype.pop=function(){var aa=this.Ic.pop();this.Cy[aa.key]=void 0;return aa};z.prototype.push=function(aa,ca){ca={key:aa,data:ca};this.Ic.push(ca);this.Cy[aa]=ca.data};z.prototype.contains=function(aa){return!!this.Cy[aa]};
z.prototype.get=function(aa){return this.Cy[aa]};z.prototype.set=function(aa,ca){var ba=this;this.Cy[aa]=ca;this.Ic.forEach(function(ha,ea){ha.key===aa&&(ba.Ic[ea]=ha)})};z.prototype.remove=function(aa){var ca=this;this.Cy[aa]=void 0;this.Ic.forEach(function(ba,ha){ba.key===aa&&ca.Ic.splice(ha,1)})};z.prototype.length=function(){return this.Ic.length};return z}(),w={pages:[{name:"pages",type:"a"}],pdf:[{name:"url",type:"s"}],docmod:[{name:"url",type:"s"},{name:"rID",type:"s"}],health:[],tiles:[{name:"z",
type:"n"},{name:"rID",type:"n"},{name:"tiles",type:"a"},{name:"size",type:"n"}],cAnnots:[{name:"annots",type:"a"}],annots:[{name:"url",type:"s"},{name:"name",type:"s"}],image:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],text:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],ApString2Xod:[{name:"url",type:"s"},{name:"rID",type:"s"}]};n=function(){function z(aa,ca,ba){var ha=this;this.FY=this.c5=!1;this.Aj=this.lO=this.rA=this.og=this.OB=this.Es=this.NB=this.Lq=
null;this.kq=new e;this.gu=new e;this.hJ=!1;this.Eh=this.sg=this.tg=this.th=null;this.$h=[];this.cK=[];this.cache={};this.timeStamp=0;this.vj=[];this.fm=[];this.xS=null;this.O4=!1;this.Sca=this.id=null;this.zV=this.m8=pa;this.Sh=0;this.hU=!1;this.A$=1;this.am={};this.Vw=0;this.zz=new a;ca.endsWith("/")||(ca+="/");ba=ba||{};this.c5=ba.disableWebsockets||!1;this.FY=ba.singleServerMode||!1;null!=ba.customQueryParameters&&Object(f.b)("wvsQueryParameters",ba.customQueryParameters);ca.endsWith("blackbox/")||
(ca+="blackbox/");this.Lq=ba.uploadData||null;this.rA=ba.uriData||null;this.NB=ba.cacheKey||null;if(this.Es=ba.officeOptions||null)this.Es=oa(this.Es);this.og=ba.rasterizerOptions||null;this.OB=ba.cadOptions||null;this.Mg=ca;this.ZR=aa;this.Ss(!0);this.ux=(new y.a(ca,null,this.sk())).aua(!this.c5,function(ea){ha.aCa(ea)},function(){return null},function(){ha.hJ=!1},function(){ha.aGa()})}z.prototype.Ypa=function(){var aa=this;return new Promise(function(ca,ba){var ha=new XMLHttpRequest,ea="".concat(aa.Mg,
"ck");ha.open("GET",ea);ha.withCredentials=aa.sk();ha.onreadystatechange=function(){ha.readyState===XMLHttpRequest.DONE&&(200===ha.status?ca():ba())};ha.send()})};z.prototype.XHa=function(aa){this.m8=aa||pa;this.zV=pa};z.prototype.joa=function(){this.jca();return this.ux.wu()};z.prototype.jca=function(){Object(ka.b)(this,void 0,void 0,function(){return Object(ka.d)(this,function(aa){switch(aa.label){case 0:return this.gu=new e,this.kq=new e,this.hJ=!1,this.id=null,this.O4=!1,[4,this.Ypa().catch(function(){})];
case 1:return aa.aa(),[2]}})})};z.prototype.aGa=function(){this.m8();this.jca();this.th&&(this.th.Vl()?this.Fj(this.th.request):this.th.Py()&&this.zV(this.th.result.url,"pdf")&&(this.th=null,this.gca()));this.Eh&&this.Eh.Vl()&&this.Fj(this.Eh.request);this.tg&&this.tg.Vl()?this.Fj(this.tg.request):this.sg&&this.sg.Vl()&&this.T7();var aa;for(aa=0;aa<this.vj.length;aa++)this.vj[aa]&&(this.vj[aa].Vl()?this.Fj(this.vj[aa].request):this.vj[aa].Py()&&this.zV(this.vj[aa].result.url,"image")&&(this.vj[aa]=
null,this.YM(Object(ja.uniqueId)(),aa)));for(aa=0;aa<this.fm.length;aa++)this.fm[aa]&&this.fm[aa].Vl()&&!this.fm[aa].kza()&&this.Fj(this.fm[aa].request);for(aa=0;aa<this.$h.length;aa++)this.$h[aa]&&this.$h[aa].Vl()&&this.Fj(this.$h[aa].request)};z.prototype.Cya=function(){return this.hJ?Promise.resolve():(this.hJ=!0,this.timeStamp=Date.now(),this.ux.oL())};z.prototype.vLa=function(){var aa=this,ca,ba,ha,ea,ma;return new Promise(function(la,ia){if(aa.Lq)ca=new FormData,ca.append("file",aa.Lq.fileHandle,
aa.Lq.fileHandle.name),aa.Es&&ca.append("officeOptions",JSON.stringify(aa.Es)),aa.og&&ca.append("rasterizerOptions",JSON.stringify(aa.og)),aa.OB&&ca.append("cadOptions",aa.OB.getJsonString()),aa.NB&&ca.append("cacheKey",aa.NB),ba=aa.Lq.loadCallback,ea="upload",ha=aa.Lq.extension;else if(aa.rA)ca={uri:aa.rA.uri,EQa:aa.rA.shareId},ca=Object.keys(ca).map(function(sa){return"".concat(sa,"=").concat(ca[sa]?encodeURIComponent(ca[sa]):"")}).join("&"),ma="application/x-www-form-urlencoded; charset=UTF-8",
ba=aa.rA.loadCallback,ea="url",ha=aa.rA.extension;else{la();return}var ra=new XMLHttpRequest,qa=Object(x.k)(aa.Mg,"AuxUpload");qa=Object(b.a)(qa,{type:ea,ext:ha});ra.open("POST",qa);ra.withCredentials=aa.sk();ma&&ra.setRequestHeader("Content-Type",ma);ra.addEventListener("load",function(){if(ra.readyState===ra.DONE&&200===ra.status){var sa=JSON.parse(ra.response);aa.ZR=sa.uri;ba(sa);la(sa)}});ra.addEventListener("error",function(){ia("".concat(ra.statusText," ").concat(JSON.stringify(ra)))});aa.Lq&&
null!=aa.Lq.onProgress&&(ra.upload.onprogress=function(sa){aa.Lq.onProgress(sa)});ra.send(ca)})};z.prototype.NFa=function(aa){this.password=aa||null;this.kq.Py()||(this.kq=new e,this.Fj({t:"pages"}));return this.kq.promise};z.prototype.iF=function(aa){this.xS=aa||null;this.kq.Py()||this.Fj({t:"pages"});return this.kq.promise};z.prototype.aC=function(aa){aa=Object.assign(aa,{uri:encodeURIComponent(this.ZR)});this.xS&&(aa.ext=this.xS);this.Aj&&(aa.c=this.Aj);this.password&&(aa.pswd=this.password);this.NB&&
(aa.cacheKey=this.NB);this.Es&&(aa.officeOptions=this.Es);this.og&&(aa.rastOptions=this.og);this.OB&&(aa.cadOptions=this.OB.mImpl);return aa};z.prototype.HGa=function(){0<this.zz.length()&&10>=this.Vw&&this.IGa(this.zz.pop().data)};z.prototype.una=function(aa){0<this.zz.length()&&this.zz.contains(aa)&&this.zz.remove(aa)};z.prototype.Fj=function(aa){aa=this.aC(aa);this.ux.send(aa)};z.prototype.Nca=function(aa,ca){10<this.Vw?this.zz.push(aa,ca):(this.Vw++,aa=this.aC(ca),this.ux.send(aa))};z.prototype.IGa=
function(aa){this.Vw++;aa=this.aC(aa);this.ux.send(aa)};z.prototype.ip=function(aa){return aa};z.prototype.l8=function(aa){this.FY&&aa?Object(fa.i)("Server failed health check. Single server mode ignoring check."):!this.NOa&&aa&&3>=this.Sh?(this.hU=!0,this.ux.wu()):3<this.Sh&&(this.FY=!0)};z.prototype.aCa=function(aa){var ca=this,ba=aa.data,ha=aa.err,ea=aa.t;switch(ea){case "upload":ha?this.wLa.reject(ha):this.wLa.resolve("Success");break;case "pages":ha?this.kq.reject(ha):na(ba,ea,this.kq)&&this.kq.resolve(ba);
break;case "config":if(ha)this.gu.reject(ha);else if(na(ba,ea,this.gu)){this.l8(ba.unhealthy);ba.id&&(this.id=ba.id);if(ba.auth){var ma=Object(f.a)("wvsQueryParameters");ma.auth=ba.auth;Object(f.b)("wvsQueryParameters",ma)}ba.serverVersion&&(this.lO=ba.serverVersion,Object(fa.g)("[WebViewer Server] server version: ".concat(this.lO)));ba.serverID?(this.Sh=ba.serverID===this.Sca&&this.hU?this.Sh+1:0,this.Sca=ba.serverID):this.Sh=0;this.hU=!1;this.gu.resolve(ba)}break;case "health":ha?this.gu.reject(ha):
na(ba,ea,this.gu)&&this.l8(ba.unhealthy);break;case "pdf":ba.url=Object(b.a)("".concat(this.Mg,"../").concat(encodeURI(ba.url)));ha?this.th.reject(ha):na(ba,ea,this.th)&&this.th.resolve(ba);break;case "ApString2Xod":ba.url=Object(b.a)("".concat(this.Mg,"../data/").concat(encodeURI(ba.url)));ha?this.am[ba.rID].reject(ha):na(ba,ea,this.am[ba.rID])&&this.am[ba.rID].resolve(ba);break;case "docmod":ba.url=Object(b.a)("".concat(this.Mg,"../").concat(encodeURI(ba.url)));ha?this.am[ba.rID].reject(ha):na(ba,
ea,this.th)&&this.am[ba.rID].resolve(ba);break;case "xod":if(ha)this.tg&&this.tg.Vl()&&this.tg.reject(ha),this.sg&&this.sg.Vl()&&this.sg.reject(ha);else if(ba.notFound)ba.noCreate||this.tg&&this.tg.Vl()&&this.tg.resolve(ba),this.sg&&this.sg.Vl()&&this.sg.resolve(ba);else{ba.url&&(ba.url=Object(b.a)("".concat(this.Mg,"../").concat(encodeURI(ba.url))));if(!this.sg||this.sg.Py())this.sg=new e,this.sg.request={t:"xod",noCreate:!0};this.tg||(this.tg=new e,this.tg.request={t:"xod"});this.sg.resolve(ba);
this.tg.resolve(ba)}break;case "cAnnots":ma=this.Eh;if(ha)ma.reject(ha);else if(na(ba,ea,ma)){ma.$X();var la=[],ia=ba.annots;ba=function(Ba){var Ca=ia[Ba].s,Aa=ia[Ba].e,Ja="".concat(ra.Mg,"../").concat(encodeURI(ia[Ba].xfdf)),Ea="true"===ia[Ba].hasAppearance?Object(b.a)("".concat(Ja,".xodapp")):null,Ma=Object(ja.range)(Ca,Aa);la[Ba]={range:Ma,promise:new Promise(function(Na,Oa){var Ta=new XMLHttpRequest;Ta.open("GET",Object(b.a)(Ja));Ta.responseType="text";Ta.withCredentials=ca.sk();Ta.addEventListener("load",
function(){Ta.readyState===Ta.DONE&&200===Ta.status&&Na({cw:Ta.response,Xo:Ea,range:Ma})});Ta.addEventListener("error",function(){Oa("".concat(Ta.statusText," ").concat(JSON.stringify(Ta)))});Ta.send()})}};var ra=this;for(ha=0;ha<ia.length;ha++)ba(ha);ma.resolve(la)}break;case "annots":if(ha)this.Eh.reject(ha);else if(na(ba,ea,this.Eh)){this.Eh.$X();var qa=new XMLHttpRequest;ma="".concat(this.Mg,"../").concat(encodeURI(ba.url));var sa=ba.hasAppearance?Object(b.a)("".concat(ma,".xodapp")):null;qa.open("GET",
Object(b.a)(ma));qa.responseType="text";qa.withCredentials=this.sk();qa.addEventListener("load",function(){qa.readyState===qa.DONE&&200===qa.status&&ca.Eh.resolve({cw:qa.response,Xo:sa})});qa.addEventListener("error",function(){ca.Eh.reject("".concat(qa.statusText," ").concat(JSON.stringify(qa)))});qa.send()}break;case "image":this.Vw--;var ua=this.vj[ba.p];ha?ua.promise.reject(ha):na(ba,ea,ua)&&(ua.result=ba,ua.result.url=Object(b.a)("".concat(this.Mg,"../").concat(encodeURI(ua.result.url))),ua.resolve(ua.result));
break;case "tiles":this.Vw--;ua=ba.rID;ma=this.$h[ua];this.$h[ua]=null;this.cK.push(ua);if(ha)ma.reject(ha);else if(na(ba,ea,ma)){for(ha=0;ha<ba.tiles.length;ha++)ba.tiles[ha]=Object(b.a)("".concat(this.Mg,"../").concat(encodeURI(ba.tiles[ha])));ma.resolve(ba)}break;case "text":ua=this.fm[ba.p];if(ha)ua.reject(ha);else if(na(ba,ea,ua)){ua.$X();var va=new XMLHttpRequest;ba=Object(b.a)("".concat(this.Mg,"../").concat(encodeURI(ba.url)));va.open("GET",ba);va.withCredentials=this.sk();va.addEventListener("load",
function(){va.readyState===va.DONE&&200===va.status&&(ua.result=JSON.parse(va.response),ua.resolve(ua.result))});va.addEventListener("error",function(Ba){ua.reject("".concat(va.statusText," ").concat(JSON.stringify(Ba)))});va.send()}break;case "progress":"loading"===ba.t&&this.trigger(r.a.Events.DOCUMENT_LOADING_PROGRESS,[ba.bytes,ba.total])}this.HGa();!ea&&aa.echo&&aa&&"apstring2xod"===aa.echo.t&&(aa=aa.echo.reqID)&&(2<=parseInt(this.lO,10)?this.am[aa].reject("Message unhandled by server"):this.am[aa].reject())};
z.prototype.Jua=function(){return Object(ka.b)(this,void 0,void 0,function(){return Object(ka.d)(this,function(aa){switch(aa.label){case 0:return[4,this.Cya()];case 1:return aa.aa(),[2,this.gu.promise]}})})};z.prototype.oua=function(aa){for(var ca=this,ba=new XMLHttpRequest,ha=Object(b.a)("".concat(this.Mg,"aul"),{id:this.id}),ea=new FormData,ma={},la=0;la<aa.body.length;la++){var ia=aa.body[la];ma[ia.id]="".concat(ia.DQ.w,";").concat(ia.DQ.h);ea.append(ia.id,ia.DQ.dataString)}aa={t:"apstring2xod",
reqID:this.A$++,parts:ma};var ra=this.aC(aa);ea.append("msg",JSON.stringify(ra));this.am[ra.reqID]=new e;ba.open("POST",ha);ba.withCredentials=this.sk;ha=new Promise(function(qa,sa){ba.onreadystatechange=function(){4===ba.readyState&&(200===ba.status?qa():sa("An error occurred while sending down appearance strings to the server"))}});ba.send(ea);return ha.then(function(){return ca.am[ra.reqID].promise})};z.prototype.noa=function(){var aa=this.lO.split("-")[0].split("."),ca=["1","5","9"];if(3!==aa.length)throw Error("Invalid WVS version length.");
if(3!==ca.length)throw Error("Invalid version length.");for(var ba=0;ba<aa.length;++ba){if(ca.length===ba||aa[ba]>ca[ba])return-1;if(aa[ba]!==ca[ba])return 1}return 0};z.prototype.bu=function(){return 0>=this.noa()};z.prototype.LS=function(){this.Eh||(this.Eh=new e,this.bu()?this.Eh.request={t:"cAnnots"}:this.Eh.request={t:"annots"},this.Fj(this.Eh.request));return this.Eh.promise};z.prototype.YM=function(aa,ca){this.vj[ca]||(this.vj[ca]=new e,this.vj[ca].request={t:"image",p:ca},this.Nca(aa,this.vj[ca].request));
return this.vj[ca].promise};z.prototype.OFa=function(aa){this.fm[aa]||(this.fm[aa]=new e,this.fm[aa].request={t:"text",p:aa},this.Fj(this.fm[aa].request));return this.fm[aa].promise};z.prototype.PFa=function(aa,ca,ba,ha,ea){var ma=this.$h.length;this.cK.length&&(ma=this.cK.pop());this.$h[ma]=new e;this.$h[ma].request={t:"tiles",p:ca,z:ba,r:ha,size:ea,rID:ma};this.Nca(aa,this.$h[ma].request);return this.$h[ma].promise};z.prototype.gca=function(){this.th||(this.th=new e,this.th.request={t:"pdf"},this.O4?
this.th.resolve({url:this.ZR}):this.Fj(this.th.request));return this.th.promise};z.prototype.Y6=function(aa){var ca=this,ba=new XMLHttpRequest,ha=Object(b.a)("".concat(this.Mg,"aul"),{id:this.id}),ea=new FormData,ma={};aa.annots&&(ma.annots="xfdf");aa.watermark&&(ma.watermark="png");aa.redactions&&(ma.redactions="redact");ma={t:"docmod",reqID:this.A$++,parts:ma};aa.print&&(ma.print=!0);var la=this.aC(ma);ea.append("msg",JSON.stringify(la));return Promise.all([aa.annots,aa.watermark,aa.redactions].map(function(ia){return Promise.resolve(ia)})).then(function(ia){var ra=
ia[0],qa=ia[1];ia=ia[2];ra&&ea.append("annots",ra);qa&&ea.append("watermark",qa);ia&&ea.append("redactions",ia);ca.am[la.reqID]=new e;ba.open("POST",ha);ba.withCredentials=ca.sk;ra=new Promise(function(sa,ua){ba.onreadystatechange=function(){4===ba.readyState&&(200===ba.status?sa():ua("An error occurred while sending down annotation data to the server"))}});ba.send(ea);return ra.then(function(){return ca.am[la.reqID].promise})})};z.prototype.T7=function(){this.sg||(this.sg=new e,this.sg.request={t:"xod",
noCreate:!0},this.Fj(this.sg.request));return this.sg.promise};z.prototype.QFa=function(){this.tg||(this.tg=new e,this.tg.request={t:"xod"},this.Fj(this.tg.request));return this.tg.promise};z.prototype.Ns=function(){return!0};z.prototype.request=function(){};z.prototype.wba=function(){};z.prototype.abort=function(){for(var aa=0;aa<this.$h.length;aa++)this.$h[aa]&&(this.$h[aa].resolve(null),this.$h[aa]=null,this.cK.push(aa));this.close()};z.prototype.pN=function(aa){this.Aj=this.Aj||{};this.Aj.headers=
aa};z.prototype.Ss=function(aa){this.Aj=this.Aj||{};this.Aj.internal=this.Aj.internal||{};this.Aj.internal.withCredentials=aa};z.prototype.sk=function(){return this.Aj&&this.Aj.internal?this.Aj.internal.withCredentials:null};z.prototype.getFileData=function(){return Promise.reject()};return z}();Object(ya.a)(n);Object(h.a)(n);Object(h.b)(n);ta["default"]=n},601:function(ya,ta,n){var pa=n(0),na=n(3),oa=n(34),ka=n(54),ja=n(219),fa=n(102),x=function(){function r(h,f,b,e,a,w){void 0===b&&(b=null);void 0===
e&&(e=null);void 0===a&&(a=null);void 0===w&&(w=null);this.kU=!1;this.Sh=0;this.hE=8;this.wca=3E3;this.JN=!1;this.h3=this.VLa(h);this.url=f?"".concat(this.h3,"/").concat(f):"".concat(this.h3,"/ws");this.JR=b;this.zE=e;this.ZB=a;this.hca=w}r.prototype.VLa=function(h){var f=h.indexOf("://"),b="ws://";0>f?f=0:(5===f&&(b="wss://"),f+=3);var e=h.lastIndexOf("/");0>e&&(e=h.length);return b+h.slice(f,e)};r.prototype.send=function(h){this.ht.readyState===WebSocket.CLOSED||this.kU||this.ht.send(JSON.stringify(h))};
r.prototype.oL=function(){return Object(pa.b)(this,void 0,void 0,function(){var h,f=this;return Object(pa.d)(this,function(){h=Object(ka.a)("wvsQueryParameters");h.bcid=Object(oa.l)(8);Object(ka.b)("wvsQueryParameters",h);return[2,new Promise(function(b,e){var a=Object(ja.a)(f.url);f.JN=!1;f.ht=new WebSocket(a);f.ht.onopen=function(){f.kU=!1;f.Sh=0;f.zE&&f.zE();b()};f.ht.onerror=function(){f.kU=!0};f.ht.onclose=function(w){w=w.code;f.ZB&&f.ZB();1E3!==w&&3E3!==w&&f.Yxa(w,b,e)};f.ht.onmessage=function(w){w&&
w.data&&(w=JSON.parse(w.data),w.hb?f.send({hb:!0}):w.end?close():f.JR(w))}})]})})};r.prototype.Yxa=function(h,f,b){Object(pa.b)(this,void 0,void 0,function(){var e=this;return Object(pa.d)(this,function(){if(this.JN)return f(),[2];this.Sh<this.hE?setTimeout(function(){e.JN?f():(e.Sh++,Object(na.i)("Failed to connect to server with WebSocket close code ".concat(h,". Reconnecting to WebViewer Server, attempt ").concat(e.Sh," of ").concat(e.hE," ...")),e.oL().then(f).catch(b))},this.wca):b(fa.a);return[2]})})};
r.prototype.wu=function(){var h;void 0===h&&(h=!1);this.Sh=0;this.JN=!0;h?this.ht.close(3E3):this.ht.close();return Promise.resolve()};return r}(),y=function(){function r(h,f,b,e,a,w,z){void 0===e&&(e=null);void 0===a&&(a=null);void 0===w&&(w=null);void 0===z&&(z=null);this.Sh=this.XM=this.id=0;this.BD=!1;this.request=null;this.hE=8;this.wca=3E3;h=this.ODa(h);this.url=f?"".concat(h,"/").concat(f,"pf"):"".concat(h,"/pf");this.eO=b;this.JR=e;this.zE=a;this.ZB=w;this.hca=z}r.prototype.ODa=function(h){var f=
h.lastIndexOf("/");0>f&&(f=h.length);return h.slice(0,f)};r.prototype.Apa=function(h){h=h.split("\n");for(h[h.length-1]&&h.pop();0<h.length&&3>h[h.length-1].length;)"]"===h.pop()&&(this.id=0);0<h.length&&3>h[0].length&&h.shift();for(var f=0;f<h.length;++f)h[f].endsWith(",")&&(h[f]=h[f].substr(0,h[f].length-1));return h};r.prototype.vca=function(){return Object(pa.b)(this,void 0,void 0,function(){var h=this;return Object(pa.d)(this,function(f){switch(f.label){case 0:return this.Sh++<this.hE?[4,new Promise(function(b){return setTimeout(function(){h.hca();
h.oL();b()},3E3)})]:[3,2];case 1:f.aa(),f.label=2;case 2:return[2]}})})};r.prototype.RDa=function(h){Object(pa.b)(this,void 0,void 0,function(){var f,b;return Object(pa.d)(this,function(e){switch(e.label){case 0:f=null,b=0,e.label=1;case 1:if(!(b<h.length))return[3,6];f=JSON.parse(h[b]);if(!f)return[3,5];if(!f.end)return[3,2];close();return[3,5];case 2:if(!f.id||Number(f.id)===this.id)return[3,4];Object(na.i)("Reconnecting, new server detected");this.wu();return[4,this.vca()];case 3:return e.aa(),
[3,5];case 4:f.hb&&Number(f.id)===this.id?this.send({hb:!0}):this.BD||this.JR(f),e.label=5;case 5:return++b,[3,1];case 6:return[2]}})})};r.prototype.WBa=function(h){Object(pa.b)(this,void 0,void 0,function(){var f,b,e;return Object(pa.d)(this,function(a){switch(a.label){case 0:if(!(3<=h.readyState))return[3,2];try{f=h.responseText.length}catch(w){return Object(na.g)("caught exception"),[2]}if(0<f)try{b=this.Apa(h.responseText),0===this.id&&0<b.length&&(e=JSON.parse(b.shift()),this.id=e.id,this.Sh=
0),this.RDa(b)}catch(w){}return this.BD?[3,2]:[4,this.R5()];case 1:a.aa(),a.label=2;case 2:return[2]}})})};r.prototype.R5=function(){return Object(pa.b)(this,void 0,void 0,function(){var h=this;return Object(pa.d)(this,function(){return[2,new Promise(function(f,b){function e(){return Object(pa.b)(h,void 0,void 0,function(){return Object(pa.d)(this,function(w){switch(w.label){case 0:b(),this.wu(),w.label=1;case 1:return this.BD&&this.Sh<this.hE?[4,this.vca()]:[3,3];case 2:return w.aa(),[3,1];case 3:return[2]}})})}
h.request=new XMLHttpRequest;h.request.withCredentials=h.eO;var a=Object(ja.a)(h.url,0!==h.id?{id:String(h.id),uc:String(h.XM)}:{uc:String(h.XM)});h.XM++;h.request.open("GET",a,!0);h.request.setRequestHeader("Cache-Control","no-cache");h.request.setRequestHeader("X-Requested-With","XMLHttpRequest");h.request.onreadystatechange=function(){h.WBa(h.request)};h.request.addEventListener("error",e);h.request.addEventListener("timeout",e);h.request.addEventListener("load",function(){h.zE&&h.zE();f()});h.request.send()})]})})};
r.prototype.oL=function(){var h=Object(ka.a)("wvsQueryParameters");h.bcid=Object(oa.l)(8);Object(ka.b)("wvsQueryParameters",h);this.XM=this.id=0;this.BD=!1;return this.R5()};r.prototype.send=function(h){var f=this,b=new XMLHttpRequest;b.withCredentials=this.eO;var e=Object(ja.a)(this.url,{id:String(this.id)}),a=new FormData;a.append("data",JSON.stringify(h));b.addEventListener("error",function(){f.wu()});b.open("POST",e);b.setRequestHeader("X-Requested-With","XMLHttpRequest");b.send(a)};r.prototype.wu=
function(){this.id=0;this.BD=!0;this.ZB&&this.ZB();this.request.abort();return Promise.resolve()};return r}();ya=function(){function r(h,f,b){this.e4=h;this.target=f;this.eO=b}r.prototype.aua=function(h,f,b,e,a){void 0===h&&(h=!0);void 0===f&&(f=null);void 0===b&&(b=null);void 0===e&&(e=null);void 0===a&&(a=null);return h?new x(this.e4,this.target,f,b,e,a):new y(this.e4,this.target,this.eO,f,b,e,a)};return r}();ta.a=ya}}]);}).call(this || window)
