/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[16],{443:function(Ba,ua,r){function pa(){return!1}function ka(aa,w,ea){if(!(w in n))return!0;w=n[w];for(var ja=0;ja<w.length;ja++){var ba=aa;var ca=w[ja];var ia=ea;if(ca.name in ba){var ha="",la=!1;ba=ba[ca.name];switch(ca.type){case "s":ha="String";la=Object(fa.isString)(ba);break;case "a":ha="Array";la=Object(fa.isArray)(ba);break;case "n":ha="Number";la=Object(fa.isNumber)(ba)&&Object(fa.isFinite)(ba);break;case "o":ha="Object",
la=Object(fa.isObject)(ba)&&!Object(fa.isArray)(ba)}la||ia.reject('Expected response field "'+ca.name+'" to have type '+ha);ca=la}else ia.reject('Response missing field "'+ca.name+'"'),ca=!1;if(!ca)return!1}return!0}r.r(ua);var ma=r(1),fa=r(0);r.n(fa);var da=r(2);Ba=r(49);var z=r(34),x=r(461),y=r(94),f=r(374),e=r(40),b=r(166),a=function(){function aa(){this.request=this.result=null;this.state=0;var w=this;w.promise=new Promise(function(ea,ja){w.resolve=function(){if(0===w.state||4===w.state)w.state=
1,w.result=arguments[0],ea.apply(null,arguments)};w.reject=function(){if(0===w.state||4===w.state)w.state=2,ja.apply(null,arguments)}})}aa.prototype.it=function(){return 1===(this.state&1)};aa.prototype.xea=function(){return 2===(this.state&2)};aa.prototype.Si=function(){return!this.xea()&&!this.it()};aa.prototype.Zda=function(){return 4===(this.state&4)};aa.prototype.rM=function(){this.state|=4};return aa}(),h=function(){function aa(){this.Qs={};this.Gb=[]}aa.prototype.pop=function(){var w=this.Gb.pop();
this.Qs[w.key]=void 0;return w};aa.prototype.push=function(w,ea){ea={key:w,data:ea};this.Gb.push(ea);this.Qs[w]=ea.data};aa.prototype.contains=function(w){return!!this.Qs[w]};aa.prototype.get=function(w){return this.Qs[w]};aa.prototype.set=function(w,ea){var ja=this;this.Qs[w]=ea;this.Gb.forEach(function(ba,ca){ba.key===w&&(ja.Gb[ca]=ba)})};aa.prototype.remove=function(w){var ea=this;this.Qs[w]=void 0;this.Gb.forEach(function(ja,ba){ja.key===w&&ea.Gb.splice(ba,1)})};aa.prototype.length=function(){return this.Gb.length};
return aa}(),n={pages:[{name:"pages",type:"a"}],pdf:[{name:"url",type:"s"}],docmod:[{name:"url",type:"s"},{name:"rID",type:"s"}],health:[],tiles:[{name:"z",type:"n"},{name:"rID",type:"n"},{name:"tiles",type:"a"},{name:"size",type:"n"}],cAnnots:[{name:"annots",type:"a"}],annots:[{name:"url",type:"s"},{name:"name",type:"s"}],image:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],text:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],ApString2Xod:[{name:"url",type:"s"},
{name:"rID",type:"s"}]};r=function(){function aa(w,ea,ja){var ba=this;this.WM=this.oS=!1;this.eh=this.rF=this.su=this.SK=this.yH=this.Fm=null;this.fm=new a;this.zp=new a;this.tB=!1;this.vf=this.Ae=this.Be=this.mf=null;this.Kf=[];this.fC=[];this.cache={};this.timeStamp=0;this.Zg=[];this.cj=[];this.BI=null;this.bS=!1;this.HY=this.id=null;this.FK=this.FU=pa;this.ai=0;this.LJ=!1;this.jW=1;this.Yi={};this.Nr=0;this.Kt=new h;ea.endsWith("/")||(ea+="/");ja=ja||{};this.oS=ja.disableWebsockets||!1;this.WM=
ja.singleServerMode||!1;null!=ja.customQueryParameters&&Object(e.b)("wvsQueryParameters",ja.customQueryParameters);ea.endsWith("blackbox/")||(ea+="blackbox/");this.Fm=ja.uploadData||null;this.su=ja.uriData||null;this.yH=ja.cacheKey||null;this.SK=ja.officeOptions||null;this.Se=ea;this.dI=w;this.yo(!0);this.cs=(new x.a(ea,null,this.Mh())).naa(!this.oS,function(ca){ba.Qfa(ca)},function(){return null},function(){ba.tB=!1},function(){ba.Tia()})}aa.prototype.W7=function(){var w=this;return new Promise(function(ea,
ja){var ba=new XMLHttpRequest;ba.open("GET",w.Se+"ck");ba.withCredentials=w.Mh();ba.onreadystatechange=function(){ba.readyState===XMLHttpRequest.DONE&&(200===ba.status?ea():ja())};ba.send()})};aa.prototype.uka=function(w){this.FU=w||pa;this.FK=pa};aa.prototype.E6=function(){this.kY();return this.cs.Kp(!0)};aa.prototype.kY=function(){Object(ma.b)(this,void 0,void 0,function(){return Object(ma.d)(this,function(w){switch(w.label){case 0:return this.zp=new a,this.fm=new a,this.tB=!1,this.id=null,this.bS=
!1,[4,this.W7()];case 1:return w.ea(),[2]}})})};aa.prototype.Tia=function(){this.FU();this.kY();this.mf&&(this.mf.Si()?this.lh(this.mf.request):this.mf.it()&&this.FK(this.mf.result.url,"pdf")&&(this.mf=null,this.jY()));this.vf&&this.vf.Si()&&this.lh(this.vf.request);this.Be&&this.Be.Si()?this.lh(this.Be.request):this.Ae&&this.Ae.Si()&&this.sU();var w;for(w=0;w<this.Zg.length;w++)this.Zg[w]&&(this.Zg[w].Si()?this.lh(this.Zg[w].request):this.Zg[w].it()&&this.FK(this.Zg[w].result.url,"image")&&(this.Zg[w]=
null,this.rE(Object(fa.uniqueId)(),w)));for(w=0;w<this.cj.length;w++)this.cj[w]&&this.cj[w].Si()&&!this.cj[w].Zda()&&this.lh(this.cj[w].request);for(w=0;w<this.Kf.length;w++)this.Kf[w]&&this.Kf[w].Si()&&this.lh(this.Kf[w].request)};aa.prototype.Jda=function(){return this.tB?Promise.resolve():(this.tB=!0,this.timeStamp=Date.now(),this.cs.bD())};aa.prototype.Mma=function(){var w=this,ea,ja,ba,ca,ia;return new Promise(function(ha,la){if(w.Fm)ea=new FormData,ea.append("file",w.Fm.fileHandle,w.Fm.fileHandle.name),
ja=w.Fm.loadCallback,ca="upload",ba=w.Fm.extension;else if(w.su)ea={uri:w.su.uri,xqa:w.su.shareId},ea=Object.keys(ea).map(function(ra){return ra+"="+(ea[ra]?encodeURIComponent(ea[ra]):"")}).join("&"),ia="application/x-www-form-urlencoded; charset=UTF-8",ja=w.su.loadCallback,ca="url",ba=w.su.extension;else{ha();return}var na=new XMLHttpRequest,qa=Object(z.j)(w.Se,"AuxUpload");qa=Object(b.a)(qa,{type:ca,ext:ba});na.open("POST",qa);na.withCredentials=w.Mh();ia&&na.setRequestHeader("Content-Type",ia);
na.addEventListener("load",function(){if(na.readyState===na.DONE&&200===na.status){var ra=JSON.parse(na.response);w.dI=ra.uri;ja(ra);ha(ra)}});na.addEventListener("error",function(){la(na.statusText+" "+JSON.stringify(na))});w.Fm&&null!=w.Fm.onProgress&&(na.upload.onprogress=function(ra){w.Fm.onProgress(ra)});na.send(ea)})};aa.prototype.Kia=function(w){this.password=w||null;this.fm.it()||(this.fm=new a,this.lh({t:"pages"}));return this.fm.promise};aa.prototype.ay=function(w){this.BI=w||null;this.fm.it()||
this.lh({t:"pages"});return this.fm.promise};aa.prototype.Nv=function(w){w=Object.assign(w,{uri:encodeURIComponent(this.dI)});this.BI&&(w.ext=this.BI);this.eh&&(w.c=this.eh);this.password&&(w.pswd=this.password);this.yH&&(w.cacheKey=this.yH);this.SK&&(w.officeOptions=this.SK);return w};aa.prototype.qja=function(){0<this.Kt.length()&&10>=this.Nr&&this.rja(this.Kt.pop().data)};aa.prototype.f6=function(w){0<this.Kt.length()&&this.Kt.contains(w)&&this.Kt.remove(w)};aa.prototype.lh=function(w){w=this.Nv(w);
this.cs.send(w)};aa.prototype.CY=function(w,ea){10<this.Nr?this.Kt.push(w,ea):(this.Nr++,w=this.Nv(ea),this.cs.send(w))};aa.prototype.rja=function(w){this.Nr++;w=this.Nv(w);this.cs.send(w)};aa.prototype.ll=function(w){return w};aa.prototype.EU=function(w){this.WM&&w?Object(da.j)("Server failed health check. Single server mode ignoring check."):!this.apa&&w&&3>=this.ai?(this.LJ=!0,this.cs.Kp()):3<this.ai&&(this.WM=!0)};aa.prototype.Qfa=function(w){var ea=this,ja=w.data,ba=w.err,ca=w.t;switch(ca){case "upload":ba?
this.Nma.reject(ba):this.Nma.resolve("Success");break;case "pages":ba?this.fm.reject(ba):ka(ja,ca,this.fm)&&this.fm.resolve(ja);break;case "config":if(ba)this.zp.reject(ba);else if(ka(ja,ca,this.zp)){this.EU(ja.unhealthy);ja.id&&(this.id=ja.id);if(ja.auth){var ia=Object(e.a)("wvsQueryParameters");ia.auth=ja.auth;Object(e.b)("wvsQueryParameters",ia)}ja.serverVersion&&(this.rF=ja.serverVersion,Object(da.h)("[WebViewer Server] server version: "+this.rF));ja.serverID?(this.ai=ja.serverID===this.HY&&this.LJ?
this.ai+1:0,this.HY=ja.serverID):this.ai=0;this.LJ=!1;this.zp.resolve(ja)}break;case "health":ba?this.zp.reject(ba):ka(ja,ca,this.zp)&&this.EU(ja.unhealthy);break;case "pdf":ja.url=Object(b.a)(this.Se+"../"+encodeURI(ja.url));ba?this.mf.reject(ba):ka(ja,ca,this.mf)&&this.mf.resolve(ja);break;case "ApString2Xod":ja.url=Object(b.a)(this.Se+"../data/"+encodeURI(ja.url));ba?this.Yi[ja.rID].reject(ba):ka(ja,ca,this.Yi[ja.rID])&&this.Yi[ja.rID].resolve(ja);break;case "docmod":ja.url=Object(b.a)(this.Se+
"../"+encodeURI(ja.url));ba?this.Yi[ja.rID].reject(ba):ka(ja,ca,this.mf)&&this.Yi[ja.rID].resolve(ja);break;case "xod":if(ba)this.Be&&this.Be.Si()&&this.Be.reject(ba),this.Ae&&this.Ae.Si()&&this.Ae.reject(ba);else if(ja.notFound)ja.noCreate||this.Be&&this.Be.Si()&&this.Be.resolve(ja),this.Ae&&this.Ae.Si()&&this.Ae.resolve(ja);else{ja.url&&(ja.url=Object(b.a)(this.Se+"../"+encodeURI(ja.url)));if(!this.Ae||this.Ae.it())this.Ae=new a,this.Ae.request={t:"xod",noCreate:!0};this.Be||(this.Be=new a,this.Be.request=
{t:"xod"});this.Ae.resolve(ja);this.Be.resolve(ja)}break;case "cAnnots":ia=this.vf;if(ba)ia.reject(ba);else if(ka(ja,ca,ia)){ia.rM();var ha=[],la=ja.annots;ja=function(oa){var wa=la[oa].s,Da=la[oa].e,Ha=na.Se+"../"+encodeURI(la[oa].xfdf),La="true"===la[oa].hasAppearance?Object(b.a)(Ha+".xodapp"):null,Ca=Object(fa.range)(wa,Da+1);ha[oa]={range:Ca,promise:new Promise(function(Ka,Ra){var Ma=new XMLHttpRequest;Ma.open("GET",Object(b.a)(Ha));Ma.responseType="text";Ma.withCredentials=ea.Mh();Ma.addEventListener("load",
function(){Ma.readyState===Ma.DONE&&200===Ma.status&&Ka({gr:Ma.response,al:La,range:Ca})});Ma.addEventListener("error",function(){Ra(Ma.statusText+" "+JSON.stringify(Ma))});Ma.send()})}};var na=this;for(ba=0;ba<la.length;ba++)ja(ba);ia.resolve(ha)}break;case "annots":if(ba)this.vf.reject(ba);else if(ka(ja,ca,this.vf)){this.vf.rM();var qa=new XMLHttpRequest;ia=this.Se+"../"+encodeURI(ja.url);var ra=ja.hasAppearance?Object(b.a)(ia+".xodapp"):null;qa.open("GET",Object(b.a)(ia));qa.responseType="text";
qa.withCredentials=this.Mh();qa.addEventListener("load",function(){qa.readyState===qa.DONE&&200===qa.status&&ea.vf.resolve({gr:qa.response,al:ra})});qa.addEventListener("error",function(){ea.vf.reject(qa.statusText+" "+JSON.stringify(qa))});qa.send()}break;case "image":this.Nr--;var ta=this.Zg[ja.p];ba?ta.promise.reject(ba):ka(ja,ca,ta)&&(ta.result=ja,ta.result.url=Object(b.a)(this.Se+"../"+encodeURI(ta.result.url)),ta.resolve(ta.result));break;case "tiles":this.Nr--;ta=ja.rID;ia=this.Kf[ta];this.Kf[ta]=
null;this.fC.push(ta);if(ba)ia.reject(ba);else if(ka(ja,ca,ia)){for(ba=0;ba<ja.tiles.length;ba++)ja.tiles[ba]=Object(b.a)(this.Se+"../"+encodeURI(ja.tiles[ba]));ia.resolve(ja)}break;case "text":ta=this.cj[ja.p];if(ba)ta.reject(ba);else if(ka(ja,ca,ta)){ta.rM();var va=new XMLHttpRequest;ja=Object(b.a)(this.Se+"../"+encodeURI(ja.url));va.open("GET",ja);va.withCredentials=this.Mh();va.addEventListener("load",function(){va.readyState===va.DONE&&200===va.status&&(ta.result=JSON.parse(va.response),ta.resolve(ta.result))});
va.addEventListener("error",function(oa){ta.reject(va.statusText+" "+JSON.stringify(oa))});va.send()}break;case "progress":"loading"===ja.t&&this.trigger(y.a.Events.DOCUMENT_LOADING_PROGRESS,[ja.bytes,ja.total])}this.qja();!ca&&w.echo&&w&&"apstring2xod"===w.echo.t&&(w=w.echo.reqID)&&(2<=parseInt(this.rF,10)?this.Yi[w].reject("Message unhandled by server"):this.Yi[w].reject())};aa.prototype.Uaa=function(){return Object(ma.b)(this,void 0,void 0,function(){return Object(ma.d)(this,function(w){switch(w.label){case 0:return[4,
this.Jda()];case 1:return w.ea(),[2,this.zp.promise]}})})};aa.prototype.Caa=function(w){for(var ea=this,ja=new XMLHttpRequest,ba=Object(b.a)(this.Se+"aul",{id:this.id}),ca=new FormData,ia={},ha=0;ha<w.body.length;ha++){var la=w.body[ha];ia[la.id]=la.lH.w+";"+la.lH.h;ca.append(la.id,la.lH.dataString)}w={t:"apstring2xod",reqID:this.jW++,parts:ia};var na=this.Nv(w);ca.append("msg",JSON.stringify(na));this.Yi[na.reqID]=new a;ja.open("POST",ba);ja.withCredentials=this.Mh;ba=new Promise(function(qa,ra){ja.onreadystatechange=
function(){4===ja.readyState&&(200===ja.status?qa():ra("An error occurred while sending down appearance strings to the server"))}});ja.send(ca);return ba.then(function(){return ea.Yi[na.reqID].promise})};aa.prototype.G6=function(){var w=this.rF.split("-")[0].split("."),ea=["1","5","9"];if(3!==w.length)throw Error("Invalid WVS version length.");if(3!==ea.length)throw Error("Invalid version length.");for(var ja=0;ja<w.length;++ja){if(ea.length===ja||w[ja]>ea[ja])return-1;if(w[ja]!==ea[ja])return 1}return 0};
aa.prototype.vp=function(){return 0>=this.G6()};aa.prototype.KI=function(){this.vf||(this.vf=new a,this.vp()?this.vf.request={t:"cAnnots"}:this.vf.request={t:"annots"},this.lh(this.vf.request));return this.vf.promise};aa.prototype.rE=function(w,ea){this.Zg[ea]||(this.Zg[ea]=new a,this.Zg[ea].request={t:"image",p:ea},this.CY(w,this.Zg[ea].request));return this.Zg[ea].promise};aa.prototype.Lia=function(w){this.cj[w]||(this.cj[w]=new a,this.cj[w].request={t:"text",p:w},this.lh(this.cj[w].request));return this.cj[w].promise};
aa.prototype.Mia=function(w,ea,ja,ba,ca){var ia=this.Kf.length;this.fC.length&&(ia=this.fC.pop());this.Kf[ia]=new a;this.Kf[ia].request={t:"tiles",p:ea,z:ja,r:ba,size:ca,rID:ia};this.CY(w,this.Kf[ia].request);return this.Kf[ia].promise};aa.prototype.jY=function(){this.mf||(this.mf=new a,this.mf.request={t:"pdf"},this.bS?this.mf.resolve({url:this.dI}):this.lh(this.mf.request));return this.mf.promise};aa.prototype.QT=function(w){var ea=this,ja=new XMLHttpRequest,ba=Object(b.a)(this.Se+"aul",{id:this.id}),
ca=new FormData,ia={};w.annots&&(ia.annots="xfdf");w.watermark&&(ia.watermark="png");w.redactions&&(ia.redactions="redact");ia={t:"docmod",reqID:this.jW++,parts:ia};w.print&&(ia.print=!0);var ha=this.Nv(ia);ca.append("msg",JSON.stringify(ha));return Promise.all([w.annots,w.watermark,w.redactions].map(function(la){return Promise.resolve(la)})).then(function(la){var na=la[0],qa=la[1];la=la[2];na&&ca.append("annots",na);qa&&ca.append("watermark",qa);la&&ca.append("redactions",la);ea.Yi[ha.reqID]=new a;
ja.open("POST",ba);ja.withCredentials=ea.Mh;na=new Promise(function(ra,ta){ja.onreadystatechange=function(){4===ja.readyState&&(200===ja.status?ra():ta("An error occurred while sending down annotation data to the server"))}});ja.send(ca);return na.then(function(){return ea.Yi[ha.reqID].promise})})};aa.prototype.sU=function(){this.Ae||(this.Ae=new a,this.Ae.request={t:"xod",noCreate:!0},this.lh(this.Ae.request));return this.Ae.promise};aa.prototype.Nia=function(){this.Be||(this.Be=new a,this.Be.request=
{t:"xod"},this.lh(this.Be.request));return this.Be.promise};aa.prototype.qo=function(){return!0};aa.prototype.request=function(){};aa.prototype.DX=function(){};aa.prototype.abort=function(){for(var w=0;w<this.Kf.length;w++)this.Kf[w]&&(this.Kf[w].resolve(null),this.Kf[w]=null,this.fC.push(w));this.close()};aa.prototype.DE=function(w){this.eh=this.eh||{};this.eh.headers=w};aa.prototype.yo=function(w){this.eh=this.eh||{};this.eh.internal=this.eh.internal||{};this.eh.internal.withCredentials=w};aa.prototype.Mh=
function(){return this.eh&&this.eh.internal?this.eh.internal.withCredentials:null};aa.prototype.getFileData=function(){return Promise.reject()};return aa}();Object(Ba.a)(r);Object(f.a)(r);Object(f.b)(r);ua["default"]=r},461:function(Ba,ua,r){var pa=r(1),ka=r(2),ma=r(34),fa=r(40),da=r(166),z=r(112),x=function(){function f(e,b,a,h,n,aa){void 0===a&&(a=null);void 0===h&&(h=null);void 0===n&&(n=null);void 0===aa&&(aa=null);this.RV=!1;this.ai=0;this.fR=this.hna(e);this.url=b?this.fR+"/"+b:this.fR+"/ws";
this.XH=a;this.Fx=h;this.Lv=n;this.XL=aa}f.prototype.hna=function(e){var b=e.indexOf("://"),a="ws://";0>b?b=0:(5===b&&(a="wss://"),b+=3);var h=e.lastIndexOf("/");0>h&&(h=e.length);return a+e.slice(b,h)};f.prototype.send=function(e){this.Ko.readyState===WebSocket.CLOSED||this.RV||this.Ko.send(JSON.stringify(e))};f.prototype.bD=function(){return Object(pa.b)(this,void 0,void 0,function(){var e,b=this;return Object(pa.d)(this,function(){e=Object(fa.a)("wvsQueryParameters");e.bcid=Object(ma.k)(8);Object(fa.b)("wvsQueryParameters",
e);return[2,new Promise(function(a,h){var n=Object(da.a)(b.url);b.Ko=new WebSocket(n);b.Ko.onopen=function(){b.Fx&&b.Fx();a()};b.Ko.onerror=function(aa){b.RV=!0;h(aa)};b.Ko.onclose=function(aa){var w=aa.code;return Object(pa.b)(b,void 0,void 0,function(){var ea=this;return Object(pa.d)(this,function(ja){switch(ja.label){case 0:return this.Lv&&this.Lv(),3E3===w?[3,3]:8>this.ai++?[4,new Promise(function(ba){return setTimeout(function(){return Object(pa.b)(ea,void 0,void 0,function(){return Object(pa.d)(this,
function(ca){switch(ca.label){case 0:return this.XL(),[4,this.bD()];case 1:return ca.ea(),ba(),[2]}})})},3E3)})]:[3,2];case 1:return ja.ea(),[3,3];case 2:h(z.a),ja.label=3;case 3:return[2]}})})};b.Ko.onmessage=function(aa){aa&&aa.data&&(aa=JSON.parse(aa.data),aa.hb?b.send({hb:!0}):aa.end?close():b.XH(aa))}})]})})};f.prototype.Kp=function(e){void 0===e&&(e=!1);this.ai=0;e?this.Ko.close(3E3):this.Ko.close();return Promise.resolve()};return f}(),y=function(){function f(e,b,a,h,n,aa,w){void 0===h&&(h=
null);void 0===n&&(n=null);void 0===aa&&(aa=null);void 0===w&&(w=null);this.ai=this.qE=this.id=0;this.Sw=!1;this.request=null;e=this.kha(e);this.url=b?e+"/"+b+"pf":e+"/pf";this.kF=a;this.XH=h;this.Fx=n;this.Lv=aa;this.XL=w}f.prototype.kha=function(e){var b=e.lastIndexOf("/");0>b&&(b=e.length);return e.slice(0,b)};f.prototype.F7=function(e){e=e.split("\n");for(e[e.length-1]&&e.pop();0<e.length&&3>e[e.length-1].length;)"]"===e.pop()&&(this.id=0);0<e.length&&3>e[0].length&&e.shift();for(var b=0;b<e.length;++b)e[b].endsWith(",")&&
(e[b]=e[b].substr(0,e[b].length-1));return e};f.prototype.tY=function(){return Object(pa.b)(this,void 0,void 0,function(){var e=this;return Object(pa.d)(this,function(b){switch(b.label){case 0:return 8>this.ai++?[4,new Promise(function(a){return setTimeout(function(){e.XL();e.bD();a()},3E3)})]:[3,2];case 1:b.ea(),b.label=2;case 2:return[2]}})})};f.prototype.mha=function(e){Object(pa.b)(this,void 0,void 0,function(){var b,a;return Object(pa.d)(this,function(h){switch(h.label){case 0:b=null,a=0,h.label=
1;case 1:if(!(a<e.length))return[3,6];b=JSON.parse(e[a]);if(!b)return[3,5];if(!b.end)return[3,2];close();return[3,5];case 2:if(!b.id||Number(b.id)===this.id)return[3,4];Object(ka.j)("Reconnecting, new server detected");this.Kp();return[4,this.tY()];case 3:return h.ea(),[3,5];case 4:b.hb&&Number(b.id)===this.id?this.send({hb:!0}):this.Sw||this.XH(b),h.label=5;case 5:return++a,[3,1];case 6:return[2]}})})};f.prototype.Nfa=function(e){Object(pa.b)(this,void 0,void 0,function(){var b,a,h;return Object(pa.d)(this,
function(n){switch(n.label){case 0:if(!(3<=e.readyState))return[3,2];try{b=e.responseText.length}catch(aa){return Object(ka.h)("caught exception"),[2]}if(0<b)try{a=this.F7(e.responseText),0===this.id&&0<a.length&&(h=JSON.parse(a.shift()),this.id=h.id,this.ai=0),this.mha(a)}catch(aa){}return this.Sw?[3,2]:[4,this.SS()];case 1:n.ea(),n.label=2;case 2:return[2]}})})};f.prototype.SS=function(){return Object(pa.b)(this,void 0,void 0,function(){var e=this;return Object(pa.d)(this,function(){return[2,new Promise(function(b,
a){function h(){return Object(pa.b)(e,void 0,void 0,function(){return Object(pa.d)(this,function(aa){switch(aa.label){case 0:a(),this.Kp(),aa.label=1;case 1:return this.Sw&&8>this.ai?[4,this.tY()]:[3,3];case 2:return aa.ea(),[3,1];case 3:return[2]}})})}e.request=new XMLHttpRequest;e.request.withCredentials=e.kF;var n=Object(da.a)(e.url,0!==e.id?{id:String(e.id),uc:String(e.qE)}:{uc:String(e.qE)});e.qE++;e.request.open("GET",n,!0);e.request.setRequestHeader("Cache-Control","no-cache");e.request.setRequestHeader("X-Requested-With",
"XMLHttpRequest");e.request.onreadystatechange=function(){e.Nfa(e.request)};e.request.addEventListener("error",h);e.request.addEventListener("timeout",h);e.request.addEventListener("load",function(){e.Fx&&e.Fx();b()});e.request.send()})]})})};f.prototype.bD=function(){var e=Object(fa.a)("wvsQueryParameters");e.bcid=Object(ma.k)(8);Object(fa.b)("wvsQueryParameters",e);this.qE=this.id=0;this.Sw=!1;return this.SS()};f.prototype.send=function(e){var b=this,a=new XMLHttpRequest;a.withCredentials=this.kF;
var h=Object(da.a)(this.url,{id:String(this.id)}),n=new FormData;n.append("data",JSON.stringify(e));a.addEventListener("error",function(){b.Kp()});a.open("POST",h);a.setRequestHeader("X-Requested-With","XMLHttpRequest");a.send(n)};f.prototype.Kp=function(){this.id=0;this.Sw=!0;this.Lv&&this.Lv();this.request.abort();return Promise.resolve()};return f}();Ba=function(){function f(e,b,a){this.ER=e;this.target=b;this.kF=a}f.prototype.naa=function(e,b,a,h,n){void 0===e&&(e=!0);void 0===b&&(b=null);void 0===
a&&(a=null);void 0===h&&(h=null);void 0===n&&(n=null);return e?new x(this.ER,this.target,b,a,h,n):new y(this.ER,this.target,this.kF,b,a,h,n)};return f}();ua.a=Ba}}]);}).call(this || window)
